### ISSUE TITLE
Turn on multiprocess compatibility for Activity Stream

### ISSUE THREAD

**Issue by Standard8** [mozilla/activity-stream#1033]
With Firefox turning on multiprocess compatibility for users, and that will soon be turned on for compatible add-ons, we should move towards making activity stream be declared as compatible.

Although it works at the moment, Firefox is implementing some shims for us to keep it working. The [documentation page](https://developer.mozilla.org/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK#Testing_with_shims_enabled) also states that using the shims may lead to performance issues.

**Comment by dmose** [comment]
Apart from the shims, presumably things not marked as multiprocess compatible are going to take different code paths and therefore have other different performance characteristics as well.  So any profiling that's folks are currently doing while in Firefox is e10s mode may not ultimately be as useful as one would hope, since AS isn't really running as an e10s add-on yet.

**Comment by Standard8** [comment]
I have a patch in progress for this. It looks like most of the incompatibilities are that `Services.obs.addObserver` has been called with two arguments instead of three.

**Comment by sarracini** [comment]
Fixed with #1042
