### ISSUE TITLE
Clicks counts on highlights look incorrect

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1034]
When running the query below we see a drastic drop in clicks on highlights on July 28th, which is when we released the new recommendation.

This is likely a bug in the code for collecting this data. I would expect a pretty small drop if people are clicking on recommendations more but this drop looks too big.

```
SELECT date, COUNT(*)
FROM activity_stream_events_daily
WHERE event IN ('CLICK', 'click')
AND source = 'FEATURED'
AND date >= '07/15/16'
AND (recommendation_url IS NULL
     OR recommendation_url = 'n/a')
GROUP BY date
ORDER BY date
```

**Comment by emtwo** [comment]
https://sql.telemetry.mozilla.org/queries/872#1492

**Comment by ncloudioj** [comment]
Turns out this issue is due to the addon always injects "recommender_type" and "url" to the `event` ping, regardless of whether the user is in the recommendation experiment or not. In Infernyx it didn't know how to handle those null values, and all non-experiment event pings therefore got dropped there. 

I think we did not want to include the experiment specific data in the generic `event` pings, as leaving a lot of null values in the pings is wasteful. Instead, those specific columns could be injected to the generic pings so that it remains stand-alone and easy to take out as the experiment finishes.

**Comment by ncloudioj** [comment]
To fix this issue, we need to:
* fix the addon not to include those two fields for non-recommendation users
* backfill the dropped event pings in the data pipeline

**Comment by ncloudioj** [comment]
The first item is now fixed!
Please leave it open until we cut the next release, then I'll finish up the data backfilling.

**Comment by emtwo** [comment]
Note: this bug also impacts blocks and deletes, not just clicks.

**Comment by ncloudioj** [comment]
Data backfill is done, we've reloaded the event pings from July 25th to Aug. 19th.
