### ISSUE TITLE
weighted highlights isn't deduping

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#1244]
1. turn on weighted highlights by setting this in about:config: 
extensions.@activity-streams.weightedHighlights = True
2. browse around 

<img width="516" alt="screen shot 2016-09-08 at 11 10 02 am" src="https://cloud.githubusercontent.com/assets/3698618/18360955/f7dc814c-75b4-11e6-8292-afb8300f985d.png">

**Comment by piatra** [comment]
My guess is the two are actually different URLs:
1. http://sfgate.com/article
2. http://sfgate.com/article#
Which are obviously pointing to the same thing but they are syntacticly different.
We do have a penalty system in place for consecutive items from the same domain, but because its a fresh profile (I assume) and there aren't a lot of items available you get that result.
I will increase the penalty and if this problem continues to show up we could force unique hosts in Highlights or think about other ways to mitigate the problem.

**Comment by piatra** [comment]
I'll be adding a fix for this in https://github.com/mozilla/activity-stream/pull/1242

**Comment by pdehaan** [comment]
FWIW, I think the URL to the article is http://www.sfgate.com/news/article/Rare-luxury-car-worth-1-4-million-destroyed-in-9208527.php

---

Thankfully it looks like our metadata proxy does a much better job of pulling a favicon.

### Embedly proxy:

```sh
$ http https://embedly-proxy.services.mozilla.com/v2/extract urls:='["http://www.sfgate.com/news/article/Rare-luxury-car-worth-1-4-million-destroyed-in-9208527.php"]' -j -v
```

![](http://www.sfgate.com/favicon.ico)
**Figure 1:** `"favicon_url": "http://www.sfgate.com/favicon.ico",`

---

### Metadata proxy:

```sh
$ http https://page-metadata.services.mozilla.com/v1/metadata urls:='["http://www.sfgate.com/news/article/Rare-luxury-car-worth-1-4-million-destroyed-in-9208527.php"]' -j
```

![](http://www.sfgate.com/apple-touch-icon.png)
**Figure 2:** `"favicon_url": "http://www.sfgate.com/apple-touch-icon.png",`

**Comment by edmoz** [comment]
i hit the jackpot!
<img width="805" alt="screen shot 2016-09-09 at 9 54 34 am" src="https://cloud.githubusercontent.com/assets/3698618/18395512/827041cc-7673-11e6-8fcd-6f30fb8a20f6.png">
