### ISSUE TITLE
Make measurements for load latency more accurate

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1268]
In reference to issue #1187, quoting @k88hudson:

"We should work on the definition/implementation for First Load Latency to make sure it’s more accurate; right now we’re using an unreliable timer on the add-on side, and we should probably we’re not accounting for message latency at the end of the event"

**Comment by dmose** [comment]
Even after the sampling event fires (which probably happens at some point after react flushes the vdom to the real dom, although it's not totally clear to me exactly when), we're not accounting for most of the time that layout takes to paint and reflow.  On my mac, that's 120ms for the majority of the work, but the last paint doesn't finish until about 600ms after that.  That said, I'm not sure _what_ exactly is being painted there (it may just be a final favicon or something), so it's quite possible that people perceive things as being usable before.

This will probably be a couple of PRs, because there's some low-hanging fruit here, and then there's some stuff that may be a lot harder to measure, if actually possible.

**Comment by dmose** [comment]
I predict https://hacks.mozilla.org/2009/06/mozafterpaint/ is going to be doing a bunch of the heavy lifting here.

**Comment by k88hudson** [comment]
Also, we should be looking at `componentDidUpdate`/`componentDidMount` instead of `componentWillReceiveProps` (which is before render)

**Comment by dmose** [comment]
Most of this is capture by the Performance project.  I've filed #1402 and added it there too.  There are a few things (particularly around user-perceived performance and paint-related stuff) that I'll file and tag with the Performance tag, but I'll wait to discuss at the next triage whether they belong in the Performance project, or if that's just for the first chunk of work that we're almost done with.
