### ISSUE TITLE
Search endlessly loading...

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#1302]
When searching from the timeline, the loading spinner continues to load endlessly. It may finally complete, and I just didn't wait long enough.

![screen recording 2016-09-15 at 10 10 am](https://cloud.githubusercontent.com/assets/3095/18559634/06064316-7b2d-11e6-99b1-f06f6bacd90b.gif)

**Comment by Mardak** [comment]
I started taking a look at this, and it's primarily because the fetch/load more pages requests 20 at a time. We should be able to pass the query to the "load more" action while returning 20 partially filtered results. There's some complications with caching / ui that needs to be cleared, but that can probably be partially addressed in #1261 where it'll probably just need to clear the cache when deleting.

**Comment by Softvision-VladBacia** [comment]
tracking this issue in https://bugzilla.mozilla.org/show_bug.cgi?id=1302733
