### ISSUE TITLE
Websites that are bookmarked from AS Timeline History, are not marked as bookmarks

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#1367]
**[Affected versions]:**
-Nightly 52.0a1 (Build ID: 20160921030221)
-Activity Stream 1.1.4-dev

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a fresh profile.

**[Steps to reproduce]:**
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Visit 4-5 websites.
3. Click on "Activity Stream" button from browser toolbar.
4. Add one of the visited websites to bookmarks from the AS context menu.
5. Observe the bookmarked websites.
6. Click on "Bookmarks" button from the AS sidebar.
7. Observe the bookmarked websites.
8. Click on Refresh button.

**[Expected results]:**
5. The bookmarked website has a star in front of the favicon.
8. When refreshing the Bookmarks page, Activity Stream Timeline History page will be displayed. 

**[Actual results]:**
5. After a website has been bookmarked, the bookmarked symbol (blue star) is displayed in front of the favicon.
8. Activity Stream Bookmark page should be displayed after the refresh has been made.

**[Notes]:**
- When accessing the context menu for a bookmarked item that is displayed in AS Bookmarks screen and that item is not marked as a bookmark, the "Remove Bookmark" option is missing.
- Below is a recording of the issue:
![bookmark behaviour](https://cloud.githubusercontent.com/assets/9248513/18748932/4b795022-80dd-11e6-95a7-dbc35caa19d7.gif)

**Comment by sarracini** [comment]
Findings:
This is likely happening because of a race condition while trying to satisfy this condition: https://github.com/mozilla/activity-stream/blob/master/common/reducers/SetRowsOrError.js#L41, specifically ```type === 'history'``` part. The type comes out of places as ```history``` but when we get metadata for that link object we smoosh the metadata type (also just a field called type) onto it, which then carries down to content and the new type of that link will be something like ```html```, thus not satisfying that condition and never going through to set a bookmark guid. Without a bookmark guid content doesn't know the link is a bookmarked link, and the star doesn't appear. The easiest way to fix this would be to rename one of (or both of) the ```type``` fields so there's no conflict

**Comment by jaredkerim** [comment]
Timeline is being removed, we will no longer work on this issue.
