### ISSUE TITLE
highlights revert to default cards intermittently

### ISSUE THREAD

**Issue by edwinwongsf** [mozilla/activity-stream#1382]
Every once in a while, maybe 1x every 24hrs i see the default firefox cards (first run) even though I have been seeing history for multiple days.  

Opening another tab results in it being proper activity stream new tab view.

**Comment by ncloudioj** [comment]
Seeing this happening on my machine, no error message was emitted in the console. I wonder if it was due to some issues in the React store, like failed to get the data, then it had to fall back to the default highlight tiles.

**Comment by tspurway** [comment]
Here is a dump of the Debug JSON, FWIW:

https://gist.github.com/tspurway/e2c8607546707779d46beab86086781d

**Comment by sarracini** [comment]
@tspurway did you have weighted highlights on?

**Comment by tspurway** [comment]
@sarracini yes, extensions.@activity-streams.weightedHighlights = true

**Comment by sarracini** [comment]
@tspurway interesting, because in the raw JSON that you gave, there were 0 entries for weighted highlights: https://gist.github.com/tspurway/e2c8607546707779d46beab86086781d#file-plaintext-json-L8459.
Maybe something went wrong with weighted highlights and since it had none it reverted back to defaults

**Comment by sarracini** [comment]
Also might be valuable to check if, when this happens, the tiles on the Timeline view are also default or not

**Comment by ncloudioj** [comment]
@sarracini might be useful for you.
* I repro'd this with "weightedHighlights = false"
* I got an empty Timeline view when this happened

**Comment by piatra** [comment]
Maybe useful to mention that with empty localstorage you will get the default cards regardless of any highlights settings or anything (try by deleting your localstorage cache). This is because we store state in localstorage and it won't be available on cold starts. So if for any reason (new profile, deleted all data, etc) your localstorage is empty you will see the default cards.

**Comment by sarracini** [comment]
@piatra this happens with a full history, and gets fixed with a refresh. So perhaps localStorage is failing silently to give us data occasionally

**Comment by Mardak** [comment]
I seem to run into this when opening a new tab for the first time in a session. Are people restarting Firefox and seeing this or is Firefox kept open and something is clearing out data?

**Comment by ncloudioj** [comment]
As @Mardak has landed #1474 , let's keep an eye on it to see if it gets fixed.
