### ISSUE TITLE
Determine shield study parameters, e.g., duration, population

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1523]
Split from #1438. @sarracini suggests @tspurway has the context to come up with the numbers/values that we need to declare for the shield study.

**Comment by sarracini** [comment]
+ specific metrics that we want to collect

**Comment by tspurway** [comment]
Our power analysis was that 10K users for two weeks would be sufficient for engagement analysis, but we would need much longer to investigate retention (fact check @emtwo?)  

For the first release of the Shield study, I think capturing event pings and measuring engagement is the highest priority.  

Metrics:  in the control (Tiles) branch, if a metric doesn't have a value that makes sense (eg. metadata_source), pick a distinct value so that it doesn't skew our existing pings.   So we might pick metric values for our Tiles event ping to be like:

```json
{
  "action": "activity_stream_event",           
  "action_position": "3",         # we already have a tile index position we can use for this
  "addon_version": "1.0.0",
  "client_id": "374dc4d8-0cb2-4ac5-a3cf-c5a9bc3c602e",
  "date": "2016-03-07",
  "event": "click or search or block or pin",      # this one might need some discussion
  "ip": "10.192.171.13",
  "locale": "en-US",
  "page": "tiles",
  "receive_at": 1457396660000,
  "source": "tiles",
  "tab_id": "1-3",
  "ua": "python-requests/2.9.1",  
  "url": "unused",   # this is only used for pocket anyway
  "recommender_type": "unused",
  "metadata_source": "screenshot"
}```

@emtwo for the `event` metric, should we use values like `tiles_event`, `tiles_search`, etc. to make sure we don't trample on existing queries/pings?

**Comment by Mardak** [comment]
For a click ping, my wip patch currently looks like this where there's no `metadata_source` but there is a `source` of "history" which comes from the tiles type that could be "affiliate" for directory links and "history" for others.

```json
{
    "action": "activity_stream_event",
    "action_position": 1,
    "addon_version": "1.1.4",
    "client_id": "b2a413f3-529d-6042-9608-871bcf94ca01",
    "event": "CLICK",
    "locale": "en-US",
    "page": "TILES",
    "session_id": "{d07c7a13-2919-174e-ac31-2a0ea3dbc59a}",
    "source": "HISTORY",
    "tab_id": "-3-3"
}
```

Is metadata_source required? Seems like we would have `page` and `source` and `metadata_source` all the same?

**Comment by Mardak** [comment]
>   "event": "click or search or block or pin",     
We'll probably want "unpin" if we have "pin"

**Comment by tspurway** [comment]
> Is metadata_source required? Seems like we would have page and source and metadata_source all the same?

We don't have to add these fields in the addon.  If they need to be set (ie.  don't have database default values), we can do that when we are processing the log in Infernyx.

**Comment by ncloudioj** [comment]
`metadata_source` is an optional field, we don't need to set it here for tiles. Infernyx will populate it with the default value.

**Comment by emtwo** [comment]
> Our power analysis was that 10K users for two weeks would be sufficient for engagement analysis, but we would need much longer to investigate retention

That's right, we should aim for 10K users per variant - with this we can make confident conclusions about daily tabs open per user, daily searches per user and daily topsite clicks per user. We'd need to run the experiment for **at least** two months in order to conclude anything about daily active users or total daily newtabs open. But for our dry run we're doing just 2 weeks.

> @emtwo for the `event` metric, should we use values like `tiles_event`, `tiles_search`, etc. to make sure we don't trample on existing queries/pings?

Won't we have an additional field that says which variant a ping is coming from? I think that would be sufficient to separate tiles vs. a-s search etc.

**Comment by sarracini** [comment]
would we be able to get a list of the criteria which deems a candidate ineligible for the shield?
off the top of my head there's: 
1. if their page is set to about:blank
2. if their locale is not en-US
3. if they're part of test pilot

@emtwo @tspurway what else?

**Comment by dmose** [comment]
If they regularly use accesibility features?

On the locale part, we _could_ consider allowing en-*, though we'd lose some amount of polish points with non-US users with things like color/colour.

**Comment by dmose** [comment]
If they regularly view some moderate amount of non-English content, most especially right-to-left language content.

**Comment by emtwo** [comment]
If they have less than "x" amount of history. X TBA

**Comment by sarracini** [comment]
This is done - and the results of the shield parameters can be found in the SHIELD.md doc found in #1579
