### ISSUE TITLE
Crash on Nightly when restarting or closing the browser if the Activity Stream add-on is installed

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#1567]
**[Affected versions]:**
-Nightly 52.0a1 (Build ID: 20161016030205)
-Activity Stream 1.1.4-dev

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Close/restart the browser from "Option menu"/"Developer toolbar".

[Expected results]:
-Firefox is closed or restarted successfully.

**[Actual results]:**
-The browser crashes.

**[Notes]:**
[Crash report](https://crash-stats.mozilla.com/report/index/f6e506cc-b96b-47de-b9eb-8d2bb2161017)

**Comment by ncloudioj** [comment]
Confirmed! Good catch.

Looks like this issue was introduced by a0c685eb77ca7a0846686d008bd9f6c26ae3ad69 , which somehow interfered with the [code](https://github.com/mozilla/activity-stream/blob/master/addon/main.js#L95) in `main.js`, and made `this` to be `undefined`. Could you take a look? @sarracini

**Comment by sarracini** [comment]
yup i'll grab this

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on A-S 1.14.0-dev-1497551877-9d19af4 and I cannot reproduce is. Thus, marking this as Verified-Fixed.
