### ISSUE TITLE
Create a "pre-release" channel

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1587]
This channel is intended to facilitate the release process of Activity Stream.

Apart from the current "release" and "dev" channels, this new "pre-release" channel will be used exclusively for baking the release at the end of each milestone. Specifically, QA engineers will be testing the builds in this channel, in turn, all bug and regression fixes will be merged into branch for this channel. Theoretically, no new features will be allowed once each "pre-release" begins. 

Note that there are two labels have been added, i.e. "Release/Blocking" and "Release/Uplifted", respectively. Those could be used to label issues and PRs over the course of release baking.

**Comment by Mardak** [comment]
To expand on the two labels, issues can be filed with the "Release/Blocking" label effectively requesting the issue to be fixed for the pre-release channel (in addition to it being fixed on "master"/"dev"). During triage, that label can be removed if it's determined that it's not necessary to fix for "release"/"pre-release".

This label is useful for developers to track which fixes need to be uplifted after being fixed on "master". Once the fix is considered good/safe on "master", it'll be uplifted to "release" and the issue relabeled as "Release/Uplifted" to track issues that should be additionally verified for release.
