### ISSUE TITLE
Page Scraper Exception: documentElement is null

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1760]
We should catch the possible exception raised when this happens:

07:30:49.356 TypeError: content.document.documentElement is null 1 page-scraper-content-script.js:28:11

Possibly catch here:

https://github.com/mozilla/activity-stream/blob/master/addon/MetadataParser.js#L43

**Comment by jaredkerim** [comment]
We should treat this as an expected failure, ie do not throw or log it, we simply fail to parse, so this case should fire the 'failed to parse' performance event and gracefully stop the parse flow.

**Comment by dmose** [comment]
@jaredkerim given that the TypeError is happening in the page-scraper-content-script, wouldn't it need to be caught there?  Which is to say that I don't see how that particular error would be catchable from MetadataParser.js, since it's not on the call stack about page-scraper-content-script (I don't think).

**Comment by dmose** [comment]
From what I can see, this could only be caught in _addWindowListeners or _sendContentMessage.  My proposal would be to simply test for the presence of documentElement in _sendContentMessage, and if it's null, communicate this back upwards (perhaps by sending back a "page-scraper-message" to be received by the listener in PageScraper.js:init?)

**Comment by sarracini** [comment]
This was fixed (https://github.com/mozilla/activity-stream/blob/master/data/page-scraper-content-script.js#L28)
