### ISSUE TITLE
Clicking on a context menu button does not close context menu

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1763]
If you click on the context menu button above a top site or a highlight, it will bring up the context menu, but then clicking the button again does not dismiss it.  Should we consider changing that so clicking the context menu button closes the menu as well?

**Comment by SoftVision-CiprianMuresan** [comment]
Yes, we should change it, because:
1. It looks like a regression from an old, fixed bug
2. The following scenario can happen:

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.7-dev or -pre-release) was previously installed on a clean profile.  
- Have enough History so that the New Tab page is populated.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and open a new tab.
2. Hover any an item from the Highlights area and click the "..." button to bring up the context menu.
3. Hover a different item from the Highlights area and click the "..." button.

[Expected result]:
- The 1st menu is dismissed while the 2nd one appears.

[Actual result]:
- The 2nd Highlights context menu can be opened while the 1st one is already opened.

[Notes]:
- All Highlights context menus can be opened this way.
- All context menus are clickable and are responsive.
- The issue is reproducible on all platforms.
- The issue is not reproducible on the Test Pilot version of Activity Stream.
![bug](https://cloud.githubusercontent.com/assets/18304511/20214501/460cfb5a-a817-11e6-9f4e-f54d84207fb5.png)

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Activity Stream RC build v1.1.7-pre-release1479402489
