### ISSUE TITLE
Activity Stream icon is missing from toolbar

### ISSUE THREAD

**Issue by nunocastro** [mozilla/activity-stream#1838]
Recently I just found out that the icon for the activity stream that should be on the toolbar is missing.

When I first installed the Activity Stream plugin the icon appeared, but after a while it was gone.
Not even when I enter customization is the icon visible/ available.

Also, I went onto the about:config and searched for the configurations of the toolbar and the entry that should display the icon is there `"action-button--activity-streams-activity-streams-link"`, but for some reason it is not displayed

**Comment by pdehaan** [comment]
@nunocastro Thanks for the report.
We recently removed support for the [old Timeline view](https://github.com/mozilla/activity-stream/projects/7) (and the toolbar icon with it), so you're seeing the latest enhanced Highlights experience on the New Tab page, where you should now see more/better highlights instead of the older, linear history Timeline view.

Ref #1466 (and #1534 PR)

**Comment by nunocastro** [comment]
@pdehaan Thanks for the heads up. 
I'm sorry to hear that, as that one of the features I used most. It allowed me a way to easily go through recent history and search it.
Without some changes that allow some degree of customization and some improvements on the main search to also include the previous timeline in the suggested results, I'll have to find something else to use for the new tab.
