### ISSUE TITLE
Increase the "limit" for the special case in the "GetRecentVisitedLinks"

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1855]
There is a special case scenario in the `GetRecentVistedLinks` that only fetches 20 links if there are not enough recently visited links. It might end up with <9 highlights as follows:

<img width="753" alt="screen shot 2016-12-07 at 12 03 51 pm" src="https://cloud.githubusercontent.com/assets/1455254/20988540/54e5306c-bc75-11e6-8ced-52287391f046.png">

**Comment by jaredkerim** [comment]
https://github.com/mozilla/activity-stream/blob/master/common/constants.js#L17

https://github.com/mozilla/activity-stream/blob/master/addon/PlacesProvider.js#L339-L341

**Comment by Mardak** [comment]
@jaredkerim you said we're still doing network calls as a fallback for pages missing metadata, so wouldn't increasing the limit to something really big like 1000 cause problems?

**Comment by jaredkerim** [comment]
@Mardak We are already making remote metadata requests for ~1000 URLs with the current weighted highlights implementation.

**Comment by Mardak** [comment]
What number were you thinking of increasing this to? If I change it from 20 to 1000, I see 30x more network requests. Also, it seemed to show fewer items on the new tab page for me until I browsed some more, so maybe there's some bug in processing these extra requests.

**Comment by jaredkerim** [comment]
@Mardak The first highlights query is unbounded and can return >1000 URLs (which it often does), which we then cap to 999 and fetch metadata including many requests to the embedly proxy, but it is date limited so will not show recent things.  We then fall back to the second query, which is capped at 20, which after applying metadata and filtering may reduce to less than 9.  

So it seems to me that we should remove the cap of 20 or increase it to at most 999 (the existing cap on the first highlights query) so that it behaves more similarly to our first highlights query.  It will create many requests to the embedly proxy which is already the case for the first highlights query, so this is not a new or surprising behaviour.  

If both queries are returning an insufficient number of highlights then it's either the case that the profile just does not have enough URLs to show, or that our SQL queries are malformed and we should alter them to allow for more results, but that should be filed as a separate ticket.  Perhaps it's worth merging the two queries so that we don't have to deal with two separate cases.

**Comment by Mardak** [comment]
I did test this with a profile that has enough history to trigger many network requests for the unbounded first query. That also resulted in the new tab page showing just the 3 default highlights, so there might really be a problem with fetching too many at once as I noted earlier when changing the second query to fetch 1000.

I'll put a patch that makes it 1000 as requested. As noted earlier, this will increase the number of network calls from 1 to up to 40 in the common case when there's enough history.
