### ISSUE TITLE
Recently visited page showed up in the top sites

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1898]
A recently visited google page (and visited just once) took a slot in my top sites. It's a bit confusing as I just dismissed a few other google pages from the top sites. Two potential issues that we may want to consider:

* Should we treat a random google search page as one of the top sites?
* Should we dedup the dismissed sites?

**Comment by emtwo** [comment]
@ncloudioj Any chance you can check if `about:newtab` has this as a tile as well?

**Comment by ncloudioj** [comment]
Nope, it is not in the about:newtab.

**Comment by ncloudioj** [comment]
So I've done some investigation on this issue. Turns out there was a side-effect of the experiment defined in 0f434c551e12a2977e5a66dd2da1953325fd909e and an earlier fix 21d356df9eaab7eea907ed7246c3ac37fbe9eb49.

In short, the "combined frecency" algorithm would give the recently visited site a fairly high score if its `rev_host` has a large number of occurrences in the `moz_places` table.

For example, say you just visited a google search result page "https://www.google.ca/search?q=foobar", and its frecency is 3085, which isn't high enough to be promoted to the Topsites group. However, note that the Topsites generating [query](https://github.com/mozilla/activity-stream/blob/master/addon/PlacesProvider.js#L357) has a "group by rev_noww", which sums up all the frecency scores of the sites that share the same non-www rev_host, in this case, it is `ac.elgoog.`. The final frecency score of "https://www.google.ca/search?q=foobar" ends up with a staggering 301761 in my test profile.

I think the frecency scoring strategy in the experiment should also consider excluding those sites from the pre-defined blocklist to avoid packing user's Topsites with sites like "google.ca" and "google.com" etc. Looks like the query currently only excludes the user dismissed/deleted sites. What do you think? @Mardak

**Comment by Mardak** [comment]
Maybe this is a good thing to try a number of experiment variants:

- frecency
- SUM(frecency)
- MAX(frecency)
- AVG(frecency)
- MAX(frecency) + AVG(frecency)

Alternatively, instead of `SUM`ming up all the pages from a given `rev_nowww`, we just combine the top page of a given `rev_host`, so that at most 2 pages (with `www` and without `www`) get combined.

**Comment by ncloudioj** [comment]
Agreed. Those all belong to the BetterTopSites project.

For this particular case, perhaps we want to avoid the phantom frecency effect. If you are a "google" or "reddit" fan, a recent random visit to those sites shouldn't be uplifted itself as the TopSites immediately.

**Comment by ncloudioj** [comment]
Also, I think `about:newtab` could be used as the reference for those experiments.

**Comment by Mardak** [comment]
@ncloudioj can you try with this branch https://github.com/Mardak/activity-stream/tree/gh1898-toprev

It should implement the "combine frecency of only the top pages of a given www and no-www" idea instead of combining frecency of all pages of the www and no-www.

Here's the single commit: https://github.com/Mardak/activity-stream/commit/403b536038aae99cae4d6bd0afef692d9bc4fa11
