### ISSUE TITLE
Truncate the title on very long highlights

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#1971]
Currently the highlights with super long titles cut into the description space and looks ugly and inconsistent with the ones without long titles:
![old](https://cloud.githubusercontent.com/assets/7219526/22034660/cbcf98e2-dca1-11e6-938e-1e6e2af51ae7.png)
By adding these lines of CSS in ```Spotlight.scss``` in the ```.spotlight-title``` class 
```css
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```
![new](https://cloud.githubusercontent.com/assets/7219526/22034661/cdd7347e-dca1-11e6-974e-268752785695.png)

**Comment by sarracini** [comment]
cc @aaronrbenson @bryanbell

**Comment by Mardak** [comment]
We probably should have a hover-on-tile title/label of the full title as I would expect many titles to end up truncated.

**Comment by dmose** [comment]
Some (possibly relevant) context that came out of research for #502: 

> The ellipsis part of this is often times referred to as "line clamping". There are lots of hacky, edge-casey solutions floating around npm and various blogs. https://bugzilla.mozilla.org/show_bug.cgi?id=1232992 is the browser bug for the CSS max-lines property, which is what we really want. That said, chances are good that we'll need to choose one of the hacks to fix this one. A particularly interesting part is going to be finding one that handles both LTR and RTL languages, which is likely to be required to get it into m-c.

**Comment by Softvision-VladBacia** [comment]
After implementing the Highlights section this issue is more and more visible. In the past I've read about Highlights tiles that they have the webpage title and a phrase or description from that webpage. Did this changed over time?

In the current implementation if the webpage displayed in a Highlight tile or Recommended by Pocket tile has a long title, then the title will be displayed also in the webpage description area.
Another case it that when the title cannot be fully displayed because it doesn't fit the space from the tile, there is no visible representation of the fact that there are more words in the title.

![long title](https://user-images.githubusercontent.com/9248513/30331126-9da5d716-97df-11e7-8a35-e3092ca68908.jpg)

In Chrome and Internet Explorer long titles that do not fit the allocated space are marked as such.

![long titles](https://user-images.githubusercontent.com/9248513/30332477-05b3234c-97e3-11e7-925e-f60dbf04caec.jpg)

**Comment by Mardak** [comment]
1 line vs 2 lines vs 3 lines:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/438537/30392164-d47004c4-9870-11e7-946d-299059eb9ada.png"> <img width="211" alt="image" src="https://user-images.githubusercontent.com/438537/30392182-e5d51f10-9870-11e7-914f-a2ec3213e441.png"> <img width="212" alt="image" src="https://user-images.githubusercontent.com/438537/30392212-fa9a27a6-9870-11e7-8044-b377cd1c6d90.png">

**Comment by Mardak** [comment]
Design says show 3 lines if we have a description. Otherwise do 4 lines.

**Comment by Mardak** [comment]
This should just be setting a `max-height` of `line-height * 3` if there's a description
