### ISSUE TITLE
Process for GitHub -> Mozilla Central code export

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1979]
- [x] build step for generating moz-build related stuff
- [x] set up / document local build process
- [ ] set up CI or script/process for exporting code from github to mozilla central
- [x] mochi tests get run in mozilla central #2002

**Comment by Mardak** [comment]
Documenting some manual steps I did to get the add-on somewhat running from a mozilla-central build:

- create `activity-streams` directory at `browser/extensions/` and update `moz.build`
- create a `moz.build` similar to other directories, e.g., 
  - `FINAL_TARGET_FILES.features['@activity-streams'] += ['bootstrap.js']`
- create a `jar.mn` file (below)
- extract bundled `xpi` into `browser/extensions/activity-streams`
- rename `install.rdf` to `install.rdf.in` replacing versions with `@MOZ_APP_(MAX)VERSION@`
- edit `package.json` entrypoint to `"main": "chrome/addon/main.js",`
- edit all `require` references to be relative, e.g., `require("addon/PlacesProvider")` to `./Places..`
- expand `data.url()`s -> `"resource://activity-streams/chrome/data/content/activity-streams.html"`

`jar.mn`:
```
[features/@activity-streams] chrome.jar:                                                               
% resource activity-streams %content/                                                                  
  content/experiments.json (experiments.json)                                                          
  content/package.json (package.json)                                                                  
  content/addon/ (addon/*)                                                                             
  content/common/ (common/*)                                                                           
  content/data/ (data/*)
```

The main packaging difference is that all the files end up inside a `chrome` directory, and the `% resource` doesn't actually do anything because it already exists pointing to the add-on root.

Alternatively, the following seems simpler but not quite right of just skipping `chrome.manifest` and including the add-on files from `moz.build` ??

`moz.build`:
```
FINAL_TARGET_FILES.features['@activity-streams'] += [                                                  
  'addon',
  'bootstrap.js',
  'common',
  'data',                                                                                              
  'experiments.json',
  'package.json'
]
```

**Comment by jaredkerim** [comment]
Closing this as completed.
