### ISSUE TITLE
`undefined` error in PreviewProvider

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2102]
Activity Stream Version: 1.3.0-dev-1485541569-7dacdd1

Error in browser console:

<img width="1124" alt="screenshot 2017-01-30 13 58 58" src="https://cloud.githubusercontent.com/assets/119884/22437035/62138e7e-e6f4-11e6-80d7-259888de86ec.png">

**Comment by rlr** [comment]
So far I've only been able to reproduce once. This should only happen with the `locallyFetchMetadata` experiment off since that uses `PageScraper.pageScraper.asyncFetchLinks()` as opposed to `PreviewProvider.asyncSaveLinks()`.

I added a bunch of extra logging to try to figure out what's going on but haven't been able to reproduce since. I'll keep poking. But if we are planning on graduating the `locallyFetchMetadata` experiment, we can possibly ignore this since it will go away at that point.

**Comment by jaredkerim** [comment]
@rlr Okay that sounds like a good analysis, if you're unable to reproduce with experiments on and off and you think it will go away soon then just close it for now.  Thanks for looking!

**Comment by jaredkerim** [comment]
@rlr just managed to reproduce, steps:

1) start activity stream in an empty profile
2) go to http://news.ycombinator.com/
3) open every link in a new tab to fill the profile with some history
4) open about:addons
5) disable activity stream
6) open and clear browser console
7) enable activity stream
8) should see 'undefined' in the browser console

It's masked by some big try catch blocks, I've narrowed it down to here:

https://github.com/mozilla/activity-stream/blob/master/addon/lib/Feed.js#L25-L57

It's being reported by line 57 so it looks like a feed is returning something wrong?
