### ISSUE TITLE
Placeholder/loading page strings are showing string ids… sometimes

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2148]
@sarracini  I was trying to demo the welcome modal, and ran into nothing being localized only showing string ids:

![screen shot 2017-02-08 at 12 11 50 pm](https://cloud.githubusercontent.com/assets/438537/22755560/8c57b2b8-edf8-11e6-813b-b6d639dcf203.png)

I didn't manage to get a screenshot, but when the modal did appear, it also showed with just string ids.

On a second run, the strings did get replaced after briefly showing the string ids, but the page title is still the id:

![screen shot 2017-02-08 at 12 13 13 pm](https://cloud.githubusercontent.com/assets/438537/22755559/8c574206-edf8-11e6-9f67-446850d8984c.png)

**Comment by sarracini** [comment]
woah.....super weird

**Comment by k88hudson** [comment]
Ah. This is probably because the state object isn't available yet, or the Localization Feed hasn't finished setting up the strings yet.

There are a couple of ways we could handle this:

a. the simple (but hackiest) way would be to add `defaultMessage`s for each component that shows up in the first run case.
b. we could move the string merging logic etc. to the reducers, which would solve this problem but result in an increase in the size of the content-side bundle (since we now have copies of all strings on both sides)

Note that if we do separate builds for each locale, the size increase for option b would be negligible.

**Comment by sarracini** [comment]
Fixed with #2154
