### ISSUE TITLE
Topsites show as screenshots when they should be icons

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#2212]
3 of my 6 top sites are stuck in screenshot form.

The Kottke.org Topsite alternates back and forth from a gloriously attractive icon to a screenshot.

<img width="487" alt="image" src="https://cloud.githubusercontent.com/assets/228979/23625032/980f2d02-025c-11e7-8baa-a38077c72b6e.png">

- http://www.salon.com/
- http://www.kottke.org/
- http://daringfireball.net/

**Comment by jaredkerim** [comment]
The logic we should implement, as described by @bryanbell is:

1) If a topsite is a TLD (root path, no subpath), it should always use the best icon it can
2) If a topsite is a non TLD (a subpath of some domain), it should use a high res icon if one is available otherwise use a screenshot

In this case we should be mostly showing icons.

**Comment by jaredkerim** [comment]
We also need to add metrics to show which things we're showing during a session

1) # number of high res icons
2) # of low res icons
3) # of screenshots

**Comment by jaredkerim** [comment]
We also need to make sure we don't block the feeds on computing screenshots the way we are now, because that can cause the feeds to block which will cause hang tight to show more often.

**Comment by jaredkerim** [comment]
This is fixed by #2115
