### ISSUE TITLE
Figure out directory structure for Mozilla Central export

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2214]
We know the directory structure of the addon in mozilla central, but we still need to figure out what it will look like when it lives in Github, and how we plan on exporting it to browser/extensions/activity-stream

**Comment by dmose** [comment]
After a bunch of discussion on Monday, we got a basic start setup: the vast majority of stuff is now living in system-addon and mozilla-central-patches, with export code written in package.json.  We basically came to the conclusion that we should iterate quickly on the directory hierarchy, rather than try to engineer too much in advance, where we lack the information to make good decisions. 

So this issue itself is done, as we've got a starting point for iteration.
