### ISSUE TITLE
Keep asking for password for internal sites.

### ISSUE THREAD

**Issue by eudennis** [mozilla/activity-stream#2239]
I don't know why, but it keep asking for the user/password for an internal site that it's in "Top Sites" section every time I open a new tab.

**Comment by sarracini** [comment]
Dupe of #2199

**Comment by ncloudioj** [comment]
Thanks for reporting this! @eudennis 

This is a known issue that was caused by the current way of favicon fetching in the add-on. For those sites with basic authentication, the add-on will trigger the prompt after the user has cleared the login info.

We're going to fix this once the favicon change for Places lands. As a temporary solution, you can type the user/password again if you want to keep that site in the top sites, or dismiss/delete it to silent the prompt.

**Comment by eudennis** [comment]
Great! I saw the @sarracini reply. Thanks for the clarification.
