### ISSUE TITLE
Port Top Sites feed to system add-on

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2309]
UI dependent on query

**Comment by k88hudson** [comment]
This is just a summary of our discussion yesterday. For this ticket, let's include:
- [ ] fetching data with `NewTabUtils` (it can use the old query for now, before the new one lands)
- [ ] getting screenshots

For screenshot fetching, it's possible that we could emit an action (e.g. `SCREENSHOT_UPDATED`) and have that action be processed by the reducers, rather than refreshing the query. If the screenshots should be updated immediately (i.e. in open tabs), they could be wrapped with the `SendToContent` action creator.

**Comment by k88hudson** [comment]
I talked to @bryanbell and he thinks it's better to load them immediately (i.e. with `SendToContent`)

**Comment by sarracini** [comment]
Fixed with #2409
