### ISSUE TITLE
port localization / jar.mn to system addon

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2313]

**Comment by sarracini** [comment]
Strings used in search for system-addon so far:
search input placeholder: "Search the Web"
search button and search input title (for a11y): "Submit search"

**Comment by Mardak** [comment]
I chatted with Standard8, and it looks like the `screenshots` system-addon has been able to just include all the locales in the xpi that gets built in Nightly. In terms of uncompressed size, all those `messages.json` total about 200KB. Currently our locales.json is about 170KB.

https://hg.mozilla.org/mozilla-central/file/tip/browser/extensions/screenshots/moz.build

Part of the reason is that relying on the build locale of Firefox might not always be appropriate, so having the other locales available to select dynamically allows for a better experience.

Given that these strings will be used in the content space, it might make sense to use `react-intl` as currently used. We'll need to not rely on `sdk/l10n` which turns out to be buggy, and we'll want to use the new fancy `Services.locale.getRequestedLocale`
