### ISSUE TITLE
Enable pocket pref for all users

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2466]
Right now the ability to turn pocket on or off is hidden behind the experiment pref, but I think we should enable the pref for all users, and then we can have:

Control: Pocket default off
Experiment: Pocket default on

And this will enable us to

1) Roll out pocket more quickly to everybody
2) Measure how many people explicitly opt in
3) Measure how many people explicitly opt out

I think this will let us roll out the feature more quickly and measure more in less time.

**Comment by k88hudson** [comment]
After discussing the details of this, it might be better to just stick with the original plan here (i.e. to only add the settings pref on by default for the variant group, and remove it entirely for the control) for a few reasons:

- flipping the pref default states and accounting for user-set states turns out to involve more work than we anticipated, for not a lot of additional useful data
- it's not clear to do with users in control who decide to turn it on – should we remove their data from the control set? etc.

What do you think @tspurway @emtwo @jaredkerim
