### ISSUE TITLE
ESC key does not close the Activity Stream's search suggestion list

### ISSUE THREAD

**Issue by cpeterso** [mozilla/activity-stream#2553]
Hitting the ESC key when typing in Activity Stream's "Search the Web" field does not close the search suggestions list like hitting ESC does in the Awesome Bar and the default about:home and about:newtab search fields.

**Comment by jaredkerim** [comment]
@cpeterso Thanks for finding that!  Because the test pilot addon will be going away shortly, we won't be fixing this in that version, but we are building a new system addon version which has not yet implemented search suggestions, so I will include this issue as part of the accessibility compliance of that feature.
