### ISSUE TITLE
Add ping-centre telemetry to Tiles (old new tab) in Nightly

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2556]
This refers to the telemetry mods we made so that Shield and AS could be fairly compared.  Let's just land this in Nightly.

**Comment by k88hudson** [comment]
After poking around a bit, I think this is going to be quite a bit more work than just porting the shield branch. Since https://bugzilla.mozilla.org/show_bug.cgi?id=1241390 removed the telemetry-related stuff that the shield branch patches (i.e. the `reportSitesAction` method and related infrastructure), which will actually break the shield branch going forward.

For that reason, I'm not sure doing this work is worth the time and effort – I'd argue that we should just focus on making our own telemetry really good.

**Comment by k88hudson** [comment]
What do you think @tspurway @Mardak @dmose?
