### ISSUE TITLE
Always return fast from Pocket Feeds

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2576]
If a Feed returns a blocking promise from its getData method, then that will block content from rendering Activity Stream and cause the 'Hang Tight!' loader to appear, which we consider a bad state.  As a best practice, we should never turn blocking promises from Feeds.  

This is happening right now in the Pocket experiment which is causing the loader to show which hurts engagement.

The offending line is here:

https://github.com/mozilla/activity-stream/blob/master/addon/Feeds/PocketStoriesFeed.js#L45

The pattern to solve this is to always return immediately from getData, and if there's no data and we need to fetch something, start a promise to fetch the data, return from getData immediately, and when we're finished retrieving the data, fire a message back into the Store with the result which the Feed can then respond to.

This should increase the perceived performance of activity stream overall which we know will increase engagement.

**Comment by k88hudson** [comment]
I don't think this is the issue here – `getData` is not being yielded on in any way (it's just called from `onAction`, while execution continues), so it can't really be refactored to be any less blocking than it already is/I don't see how returning early would have any effect

It's definitely interesting that there is a perf regression here though – maybe it's caused by the additional local storage parse time? Or the additional network requests?

**Comment by jaredkerim** [comment]
Yeah, the TopSites and Highlights feeds will block the front end from being available but the Pocket feed does not so you're right this shouldn't affect showing the 'Hang Tight' loader.  Closing this.
