### ISSUE TITLE
Recent Bookmarks Section 

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2621]
This section will show up directly after the Top Stories section and will contain your three (max) most recent bookmarks.  

<img width="782" alt="image" src="https://cloud.githubusercontent.com/assets/25276/26357478/6188eff6-3f9d-11e7-863c-947dea29cf53.png">

If you don't have any  bookmarks, the section will look like:
 
<img width="778" alt="image" src="https://cloud.githubusercontent.com/assets/25276/26357620/d7206c62-3f9d-11e7-8dfa-c4d472c93ff9.png">

**Comment by piatra** [comment]
Several question that I came across while working on this issue:
- [ ] do we want to show default browser bookmarks? The issue with these to keep in mind is that they do not have any metadata available at the beginning.
- [ ] this new section gets cutout when highlights are also expanded. Not sure if actually an issue but the screenshot does not provide a full page view.
- [ ] what should happen if you have AS open in one tab and you add a bookmark. Does it get updated? And any other interaction details would be helpful here. Same goes for the scenario in which you remove a bookmark.
- [ ] Related to the context menu: Should we keep the `Dismiss` button here? Should we keep the `Delete from history` button?

@rlr needinfo? or please mention someone else who has more context.

**Comment by rlr** [comment]
@aaronrbenson is the best to answer most of these.

Regarding the 3rd point, for now we don't keep all the activity stream instances in sync. But we will on the system addon. So for now, don't worry about that part.

For the source in metrics pings, it should be something like BOOKMARKS.

**Comment by aaronrbenson** [comment]
Agree with Ricky on those items. For the others, my thoughts are:

- *Do not* show default bookmarks (since this is intended to be your recent bookmarks. we’ll have a better zero state implemented so it’s at least not a blank section.

- Not worried about the collapsing issue

- Context menus can stay the same. Maybe folks want it off their new tab, or out of their history, but want to keep the bookmark (shrug). Just want to point out it should have the Remove Bookmark option as the first item, just how bookmarked items appear in Highlights currently.

**Comment by piatra** [comment]
Pull request https://github.com/mozilla/activity-stream/pull/2659
