### ISSUE TITLE
Visit Again Section

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2622]
The Visit Again section will have six (two rows) of cards sorted in descending recentcy, for sites that you have visited and that have metadata, deduplicated based on domain.  In the case you have no history, then this section should not be shown.

<img width="782" alt="image" src="https://cloud.githubusercontent.com/assets/25276/26357741/48f751d4-3f9e-11e7-84cf-9b76b4352ce8.png">

**Comment by piatra** [comment]
Full page design: https://mozilla.invisionapp.com/share/VHBRBK5SJ#/screens/234235604_NewTab_-_All
Preferance panel with text for this new section: https://cl.ly/3Y3v0c373A3u/o

**Comment by piatra** [comment]
As proposed in the retrospect, the experiment to review the implementation.
Checklist:
- [ ] use [`getRecentlyVisited`](https://github.com/mozilla/activity-stream/blob/4e8ffa7543f38a3429beb2819af6cfad35de73da/addon/PlacesProvider.js#L511) from places provider with a limit of 24 items (this is just an assumption that it would be enough, we only display 6 but it also involves deduping)
- [ ] create a new component `RecentlyVisited` similar to the bookmarks and highlights
- [ ] create a new method in `selectAndDedupe` that calls on `dedupe.one` (from the fancy-dedupe module). This shouldn't be in selectors.js because it also involves writing a specific [createKey](https://github.com/mozilla/activity-stream/blob/4e8ffa7543f38a3429beb2819af6cfad35de73da/common/selectors/selectAndDedupe.js#L5) for the method.
- [ ] create a VisitAgainFeed based on BookmarksFeed. This needs to refresh on every `RECEIVE_PLACES_CHANGES` which is triggered on every update of the places db since we always need the most recent items.
- [ ] add new *_REQUEST and *_RESPONSE actions + prefs to show hide the section and collapse it
- [ ] VisitAgain component needs to filter out results with no images (as specified in requirements) maybe something like `this.props.sites.filter(s => s.images.length > 0)` in addition to the deduping.

**Comment by piatra** [comment]
@rlr can you please review the checklist. Let me know if you don't agree with something or if you think I'm missing any big piece that I haven't described in the implementation.

**Comment by rlr** [comment]
This looks good. I think we should look into having all the deduping/filtering/etc logic in the Feed. So whatever is in the feed is what will get displayed. Right now we have this logic split between the addon side and the react side which isn't ideal. Thoughts on that?

**Comment by piatra** [comment]
👍
