### ISSUE TITLE
add <meta> CSP tag to the system-addon HTML

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2645]
Since resource: URIs are framable, it come up at the security review that we should add a CSP <meta> tag.   dveditz suggested that at the very least we want no inline scripts and no ancestor framing.  We may be able to use the CSP from the SDK add-on as a starting point.

**Comment by k88hudson** [comment]
I don't think we'll be able to allow no inline scripts because of snippets, is that known/expected @dmose?

**Comment by dmose** [comment]
@k88hudson No, I don't think that was clear at the time of the security review.  
Maybe check if tiles has a CSP, and if so, what it does... it's hard for me to imagine us making security worse.  If not, maybe ping dveditz (though he's on PTO today, at least, sez his IRC nick).

**Comment by sarracini** [comment]
We're going to do Content-Security-Policy-Report-Only since we're not sure if we'll break some stuff for onboarding and snippets right now. So @ncloudioj is going to give us an endpoint so we can dump some logs there and see if we break anything. If the logs show that we're ok then we can switch out of Report-Only. Right now this is blocked on getting that endpoint

**Comment by ncloudioj** [comment]
@k88hudson @sarracini Is it possible to add a custom field to the csp report? For instance, `"action": "activity_stream_csp_report"`.

This allows us to re-use the existing endpoint without any extra change, and we can easily process those logs if necessary.

**Comment by k88hudson** [comment]
@ncloudioj  AFAIK unfortunately not, the CSP report is generated/sent automatically by the browser

**Comment by ncloudioj** [comment]
Okay, will make a new Onyx endpoint for this.

**Comment by ncloudioj** [comment]
The new endpoint will be:

* stage: https://onyx_tiles.stage.mozaws.net/v4/links/activity-stream/csp
* prod: https://tiles.services.mozilla.com/v4/links/activity-stream/csp

It expects a JSON report as follows:
```json
{
  "csp-report": {
    "document-uri": "http://example.org/page.html",
    "referrer": "http://evil.example.com/",
    "blocked-uri": "http://evil.example.com/evil.js",
    "violated-directive": "script-src 'self' https://apis.google.com",
    "original-policy": "script-src 'self' https://apis.google.com; report-uri http://example.org/my_amazing_csp_report_parser"
  }
}
```

Onyx will check the existence of `csp-report`, otherwise, it'll treat it as a malformed ping.
