### ISSUE TITLE
Define "activity-stream-session" payload&schema for the system addon 

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2653]
Let's use this bug to kick off the discussion about "activity-stream-session" schema&payload definition.

We can start from the current version defined [here](https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/data_events.md#session-end-pings)
```js
{
  "action": "activity_stream_session",
  "client_id": "26288a14-5cc4-d14f-ae0a-bb01ef45be9c",
  "addon_version": "1.0.12",
  "locale": "en-US",
  "page": ["about:newtab" | "about:home"],
  "session_duration": 4199
}
```

@dmose Could you add those timestamp fields you mentioned earlier for calculating the "session_duration"?

Comparing to the Test Pilot counterpart, I've also listed out all the missing fields as follows,
* `load_reason` and `unload_reason`
* `load_latency`
* `user_prefs`
* `history_size` and `total_bookmarks`
* `topsites` and `highlights` related stats (size/#tippytop/#screenshot)

Do we want to include any of those fields in the session pings?

@emtwo @tspurway @k88hudson

**Comment by k88hudson** [comment]
`load_reason` and `unload_reason` are no longer being collected, so they can be omitted.

I think `load_latency` will be replaced with whatever values @dmose is adding for performance

**Comment by k88hudson** [comment]
`history_size` and `total_bookmarks` might be useful but they haven;t been implemented yet

**Comment by emtwo** [comment]
`topsites` and `highlights` metrics are also useful but likely not implemented yet.

Since there are a bunch of stuff that's not yet implemented, @ncloudioj I suppose we could either add those fields and populate them on the server or just add them as needed. What do you think is better?

**Comment by ncloudioj** [comment]
@emtwo For those fields that we know we're going to include sooner or later, I'd rather have them in the database first and use default values to populate them on the server. I think this applies to `topsites` and `highlights` metrics. For `history_size` and `total_bookmarks`, we can add them later if needed.

How about the `user_prefs`? I wonder if it's too messy to decode the bitmask back to the actual pref strings in SQL. Your call :) @emtwo

**Comment by dmose** [comment]
As Kate said, load_latency will go away.  Anything not otherwise noted is intended to be a [DOMHighResTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp) (aka a double of milliseconds, with a .5 microsecond precision). 

In contrast to what we decided the other day, I think these actually do want to be absolute numbers rather than counting the start time at zero, because we don't know what we're going to want to include prior to the page load start in the future (eg preload_navigation_start)


```
load_trigger
visibility_event_fired
search_box_painted
top_sites_data_ready
top_sites_painted
spinner_start_painted?
spinner_removed_painted? 
first_real_interaction
display_done
```

The question marks are after a couple that I'm not really sure how much effort we'd go to get the "post paint" time; getting the rendering time may well be good enough, in which case they might want to be named differently.

We'll also want some non-timestamps, though it's not yet entirely clear that we'll be able to get all of the following data.

```
home_load_trigger_type: enum(first_window_open || subsequent_window_open || home_window_button_click)
newtab_load_preloaded: boolean
```

There are a few others that we'll want, that I haven't entirely figured out how to structure:

time_between_search_keystroke_and_char_visibile (list?)
time_between_search_keystroke_and_autocomplete_menu_painted (list?)

event handlers running > 10ms
code running on the main thread (which we've got another bug for around here somewhere).

That's the basic set.  Some more may shake out as the bugs get filed in the next small number of days.

**Comment by dmose** [comment]
Hmm, I think about:home and about:newtab loads can also both be triggered by session restore, so we'll want home_load_trigger_type to also have session_restore, and we're also going to want newtab_load_trigger_type: enum(BrowserOpenTab || session_restore || also "other"?).

**Comment by dmose** [comment]
Oh, and also "url_bar" for both URLs.

**Comment by dmose** [comment]
In order to make this discussion go more easily, I've created a branch where we can all edit the documents as we discuss them here.  I've given everyone already mentioned in this issue "collaborator" access to my repo, so you should be able to push commits to the branch right away.  So far, I've just added a basic performance proposal with some unfinished bits to v2-system-addon/data-events.md.  Feel free to comment.

**Comment by dmose** [comment]
https://github.com/mozilla/activity-stream/pull/2660/files

**Comment by ncloudioj** [comment]
This is fixed via [splice](https://github.com/mozilla/splice/commit/39bbef133492f5e8b4933844b2c61c6a227f4ee2)
