### ISSUE TITLE
avoid content-process jank by collecting slow event handler telemetry

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2669]
The idea is that all event handlers set a 10-ms timeout.  If the timeout fires, then we append a stack to the list of slow event handlers in the session performance object.  

We'll need to figure out what to do about REALLY slow event handlers.  We could consider having a single event handler call simply accumulate how many times the timer has fired during that call and then append a tuple like [50ms, "stack trace"] to the "slow_event_handlers" property in the performance object for the session before the handler returns.

It might be reasonable to implement this as a higher-order function that we use to wrap each event handler.

Note that the schema work is still in progress, and is happening in #2653 and https://github.com/mozilla/activity-stream/pull/2660/files

CC @digitarald

**Comment by digitarald** [comment]
If the event handler is delayed, the 10ms timeout doesn't help. Also 10ms is rather short, even less than a frame. I would focus on delays larger than 50ms.

What you can measure is how long an event waited in the queue (`performance.now() - event.timeStamp`) and how long the rest of the frame takes. Since you don't know when the paint happens, you can get close by knowing when the next frame starts. The event handler would register a `rFA` (which will be executed after event handling but before paint) which sets up a `setTimeout`. The timer will be executed beginning of the next frame, giving you the end time for tracking.

Depending on how many events you handle it might make sense to only instrument a sample of 10% or so.

**Comment by dmose** [comment]
@digitarald Thanks, that's super helpful!

Does "sample of 10%" mean 10% of the time that any given event handler fires?  Or all of the events of 10% of the users?

**Comment by digitarald** [comment]
> Does "sample of 10%" mean 10% of the time that any given event handler fires? Or all of the events of 10% of the users?

10% of events from all users.

**Comment by dmose** [comment]
@digitarald OK, thanks re the 10% clarification.  One more question:

> What you can measure is how long an event waited in the queue (performance.now() - event.timeStamp) and how long the rest of the frame takes. Since you don't know when the paint happens, you can get close by knowing when the next frame starts. The event handler would register a rFA (which will be executed after event handling but before paint) which sets up a setTimeout. The timer will be executed beginning of the next frame, giving you the end time for tracking.

Is the setTimeout part of the above still true, even given the 3-event-queue refactoring described in [Quantum Flow Engineer Newsletter 11](https://ehsanakhgari.org/blog/2017-06-02/quantum-flow-engineering-newsletter-11)
?

**Comment by dmose** [comment]
@digitarald does it make sense to, in addition to this work, do a 50ms heartbeat timer for each about:newtab and about:home as you mentioned in https://github.com/mozilla/activity-stream/issues/2005#issuecomment-298095620 or is that overkill??

**Comment by digitarald** [comment]
As it can have impact on performance I would only enable it on a 1% longitudinal sample for a start

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1448354
