### ISSUE TITLE
Top Stories that are bookmarked are not added to Recent Bookmarks section

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2718]
**[Affected versions]:**
- Firefox 53 and up
- Activity Stream Build: 1.14.0-dev-1497445690-a315655

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- Top Stories are enabled.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Bookmark a Top Stories item.
3. Observe Recent Bookmarks section.
 
**[Expected results]:**
- The bookmarked Top Story item is added to Recent Bookmarks section.

**[Actual results]:**
- The item is marked as bookmarked in Top Stories section but it is not added in Recent Bookmarks.

**Comment by piatra** [comment]
Explanation: When you bookmark Pocket Top Stories they get added to moz_bookmarks but not to moz_places. You end up with a bookmark to a page you never visited, and there is no url information in moz_bookmarks.

Technical checklist:
- [ ] use `PlacesUtils` to insert a history visit
- [ ] In [ActivityStreams](https://github.com/mozilla/activity-stream/blob/f406ecd40ae85dccee410ec624665bcb9e294932/addon/ActivityStreams.js#L227) call out to `PlacesUtils` to insert a visit.
  - This will insert a visit for any bookmark added.
  - The payload available in `_respondToPlacesRequests` is insufficient to determine the origin source of the bookmark request

```
{"type":"NOTIFY_BOOKMARK_ADD","meta":{"broadcast":"content-to-addon"},"data":"https://dailystoic.com/alain-de-botton/","workerId":"{2be55b1d-07f4-c047-aa16-7bf1eaaa2fc4}"}
```
  - Is it worth augmenting `NotifyBookmarkAdd` action with source information in order to target Pocket bookmarks?

**Comment by rlr** [comment]
Oh wait, I think we maybe only need to remove the `AND p.last_visit_date IS NOT NULL` from the getBookmarks query? no?

**Comment by rlr** [comment]
I tried that and it kind of fixes the issue except that now we show default bookmarks that ship with Firefox. And metadata never seems to show up for them. @jaredkerim is there a limitation with the page scraper that requires a user to have actually visited the page before?

**Comment by piatra** [comment]
The good part is that Pocket Stories you bookmark will have metadata and image.
