### ISSUE TITLE
Data review of data_events.md and data_dictionary.md

### ISSUE THREAD

**Issue by fmarier** [mozilla/activity-stream#2724]
Here are some questions and things I've noticed in [data_events.md](https://github.com/mozilla/activity-stream/blob/14fef9c2fbc67858b5afe98b6c371f42869bd8bd/docs/v1-test-pilot/data_events.md) and [data_dictionary.md](https://github.com/mozilla/activity-stream/blob/f24208fcd675e5332a732f89b87e62a90ce43dc0/docs/v1-test-pilot/data_dictionary.md).

## `data_dictionary.md`

- `provider`: Is there a fixed list or can arbitrary service URLs end up here? Is the URL limited to the origin (i.e. no path)?
- The `receive_at` field is missing from the table but is present in the `session` log example.
- `source`: missing `"pocket"`

## `data_events.md`

- What goes after the `#` in the `url` field of `activity_stream_session` pings? Can any user data sneak in there or is it just hard-coded anchors from the HTML pages?
- Session end pings | Basic event: `unload_reason` is missing some states in the JSON (`search`, `click`, `close`)
- Bad app state pings | Highlight without an image: Are we collecting any kind of identifier about the highlight that doesn't have an image? It doesn't look like it, but I just want to confirm.

**Comment by fmarier** [comment]
@tspurway Is there any other documentation I should review as part of the data review besides the two above?

**Comment by jaredkerim** [comment]
Let's re-review these fields in the context of the pull request which is updating them: https://github.com/mozilla/activity-stream/pull/2610/files

**Comment by fmarier** [comment]
@tspurway @jaredkerim The above questions are the only thing left before completing the data review. If you can answer those, I can prepare a summary for Benjamin and hopefully finish it by the end of the month.

**Comment by tspurway** [comment]
Just to clarify that we should be looking at the documents in the `/activity-stream/docs/v2-system-addon` directory, as some of these comments are only relevant to the `/activity-stream/docs/v1-test-pilot` directory, which is no longer under development.  The PR is changing the system addon documents.

With that in mind, here are answers to the above questions:

## `data_dictionary.md`

- `provider`: this field is no longer collected
- `receive_at`: was mislabeled `timestamp` and has been fixed in the PR #2610
- `source`: the source for Pocket data will be `pocket` - this change is currently in PR  #2911

## `data_events.md`

- What goes after the `#` in the `url` field of `activity_stream_session` pings?  
  - The session ping no longer tracks a `url` field
- Session end pings | Basic event: `unload_reason` is missing some states in the JSON (`search`, `click`, `close`).  
  - The session ping no longer tracks `unload_reason`
- Bad app state pings | Highlight without an image: Are we collecting any kind of identifier about the highlight that doesn't have an image? It doesn't look like it, but I just want to confirm.  
  - we no longer have the bad app state ping

@fmarier let me know if you have any other questions.  I'd really like to get a r+ and merge PR #2610
