### ISSUE TITLE
Intermittent failure e10s browser_onboarding_tours.js Linux debug

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2830]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1381335

```
FAIL | browser/extensions/onboarding/test/browser/browser_onboarding_tours.js | Uncaught exception
Should load onboarding overlay - timed out after 30 tries.
```
Linux: https://treeherder.mozilla.org/logviewer.html#?job_id=112532102&repo=pine&lineNumber=7600
Linux64: https://treeherder.mozilla.org/logviewer.html#?job_id=112599818&repo=pine&lineNumber=4111

```
Found an unexpected tab at the end of test run: about:newtab
```

**Comment by dmose** [comment]
@gasolin can you take a look at this?  It's one of the last things that's preventing us from preffing on Activity Stream in Nightly...

It _seems_ to be a valid failure, and it looks as though the Onboarding constructor in onboarding.js is not executing for about:newtab, even when I force browser.onboarding.enabled to true.  It's possible, though that that's because I've been trying use to `debugger` statements to get a sense of what's been executing, and those are sometimes unreliable.

For what It's worth, this fails on a linux x64 opt build for me every time:

```bash
./mach mochitest --setpref browser.onboarding.enabled=true --setpref browser.newtabpage.activity-stream.enabled=true -f browser browser/extensions/onboarding/test/browser/browser_onboarding_tours.js
```

Do you also see that failure?

**Comment by dmose** [comment]
As it turns out the debugger; statement was being flaky.  Digging in further now.

**Comment by dmose** [comment]
Excitingly, the thing that I was chasing was a different bug that was 100% reproducible: if the test browser window is too small (eg because it's in a tiny VMWare window), then the close button gets cropped by the viewport, and the test never finishes for either about:home or about:newtab.

On the up side, debugging that gave me a pretty good understanding of the code.

Right now, I'm just trying to reproduce it.  I've done about 50 runs on my Linux VM without hitting it once, 50 more or so to go.  I've also kicked off a try build to see if I can get it there, and then use a "one click loaner" to debug further...

**Comment by dmose** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=f8810bb26a3081d9fe2f8eea045b4f0cad847c4e

**Comment by dmose** [comment]
OK, so 100 local runs didn't reproduce this once, nor did any of the runs in that try link above.  We did see this yesterday on pine, so I'll leave this open for another day or so, and then close under the assumption that some unknown code change made this problem go away.

**Comment by dmose** [comment]
This hasn't gone away, it turns out:

https://treeherder.mozilla.org/logviewer.html#?job_id=114062262&repo=pine&lineNumber=5613

I'm trying to debug using a taskcluster loaner now...

**Comment by dmose** [comment]
I can reliably reproduce this on a one-click loaner.   One thing I've learned just by watching it fail is that in the failure case, the overlay never gets overlaid at all, and the test hangs waiting for it.

Unfortunately, because these one-click loaners are "spot instances", they get killed out from under me while I'm debugging at random moments (3 times at least today already).  So I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1380882 to get a non-spot loaner.

I've also learned how to quickly hack up the artifact build scripts to be able to pull their artifacts from a pine build.  Once this is going, I should be able to iterate on JS changes in-place to debug.

**Comment by dmose** [comment]
With some taskcluster debugging help from dustin, it turns out that it wasn't being killed because it was a spot instance, but because of some odd default taskcluster settings (in particular deadline and maxRunTime) due to a (now-reopened) taskcluster regression.  Further, those settings can be edited when one is creating the spot loaner, so I'm up and going again...

**Comment by dmose** [comment]
Then again... I just had another instance killed about an hour in, despite my editing those params.

That said, I was able to make a build using the artifacts from the run that failed, but even there I couldn't reproduce the error.  I'm guessing it's because the timing is different when pulling the JS from the tree than it is when it comes from the omnijar file.

**Comment by Mardak** [comment]
Pushed onboarding try with latest patches: https://treeherder.mozilla.org/#/jobs?repo=try&revision=583d77d718566376cd43c969b786ca23ade0ebdf

**Comment by Mardak** [comment]
On Linux debug, there's 12 out of 20 failing across the various tests including tours, tourset, notification{,2,3,4}.
Linux64 debug has 4 out of 20 failing

No failures for either Linux opt builds. Some reason osx ran a different set. No failures on windows.

**Comment by Mardak** [comment]
Sorry dmose, I ended up grabbing this. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1381335

Just need to increase initial check to be greater than 30.

**Comment by sarracini** [comment]
Closed via: https://bugzilla.mozilla.org/show_bug.cgi?id=1381335#c12 
@Mardak is on 🔥

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/ec0dc3ef3bf7
