### ISSUE TITLE
Activity Stream survey showing up even when AS is still installed?

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2866]
Mentioned by Nate (via Slack):

<img width="1063" alt="screen shot 2017-07-16 at 10 02 37 am" src="https://user-images.githubusercontent.com/139451/28248678-e795bbde-6a0d-11e7-9144-87982bc21b05.png">

Version: Build: 1.15.0-dev-1500168405-e19a42b

**Comment by k88hudson** [comment]
Is there a way we could ask existing users to use nightly :D?

**Comment by johngruen** [comment]
k88hudson: we don't uninstall the experiment. You guys should eventually push a version of the experiment that looks for the AS about:config pref and autouninstalls when it's landed.

**Comment by jaredkerim** [comment]
I think the current plan is to keep the current version of the Test Pilot addon alive without any further changes until the system addon makes its way out to release at which time we will deploy an update to the Test Pilot audience to close and uninstall the Test Pilot version so that we can seamlessly transition our existing Test Pilot audience directly over to the system addon.
