### ISSUE TITLE
Description overflows for the Pocket tile 

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2899]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1381703
<img width="827" alt="screenshot_2017-07-17_17 20 52" src="https://user-images.githubusercontent.com/1455254/28332660-94f878d2-6bc3-11e7-81b5-e67ae8a88cb7.png">

As we're porting Pocket to system addon, we might want to take a look at it.

**Comment by Mardak** [comment]
From hugo:
> this only happened for that particular story, not the position of the story.
> We removed the story from the global recs feed and the new story have the same issue. My sense is that the issue is with how that particular item was being rendered.
> This is the item itself: http://ben-evans.com/benedictevans/2017/7/13/content-isnt-king
> Not sure if it matters, but it doesn’t look like it has an image like the rest.

I would guess normally the text is hidden by https://github.com/mozilla/activity-stream/blob/a315655c9fefc9a3762dd967636ae66b15e28218/content-src/components/Spotlight/Spotlight.scss#L116

**Comment by piatra** [comment]
Is this issue still reproducible? Is it possible that it was fixed by another pull req. Right now I am seeing: 
<img width="275" alt="screen shot 2017-07-24 at 16 49 17" src="https://user-images.githubusercontent.com/810040/28529293-746accc4-7090-11e7-8f10-90208a14cb67.png">
<img width="272" alt="screen shot 2017-07-24 at 16 49 10" src="https://user-images.githubusercontent.com/810040/28529292-74656978-7090-11e7-9962-a9ab88b732f7.png">
Even though the description is longer it gets correctly clipped.

**Comment by Mardak** [comment]
It sounds like it wasn't happening for all stories. At least two separate reports had the exact same offending story screenshotted: https://bug1381703.bmoattachments.org/attachment.cgi?id=8887278

**Comment by Mardak** [comment]
@k88hudson says this should be fixed on system addon

**Comment by jaredkerim** [comment]
Closing this as fixed.
