### ISSUE TITLE
Hide Stories/Pocket preference section for locales that have it off by default

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2973]
Morphed issue to be hiding the pref section. See https://github.com/mozilla/activity-stream/issues/2973#issuecomment-318465880

-----

Original issue below:

Append "|  Limited Language Support" to the title in prefs for Pocket Stories so it's clear to locales that don't have stories enabled why that's the case.

![screen shot 2017-07-26 at 1 22 03 pm](https://user-images.githubusercontent.com/139451/28637025-b30cfd78-7205-11e7-98d5-f229c143f142.png)

Font color: #4A4A4F 50% opacity
Font size: same as description text (14px)

**Comment by mconnormoz** [comment]
General Q: My understanding was that we were not going to enable the feature for any locale or geo outside of the P1 geos.  I assumed we would hide all related UX instead of exposing a feature without local content, so this bug is confusing.

Design feedback:

* This won't work with the current string (much longer), and probably doesn't work well in other translations (think German).  If we want to add a disclaimer, we should do it as a separate text block to avoid problems.
* We shouldn't show the text block in any language/geo where we have support, because that would be confusing, IMO.
* Limited language support doesn't explain much.  More accurate would be "we only have English and German stories available" but I still think the path of least confusion is "don't show them the feature"

**Comment by Mardak** [comment]
Sounds like for shield beta 56 users, we might need to add the string or hide the pref pane section based on whether we turned on the Section by default. Users could still toggle it from about:config

**Comment by mconnormoz** [comment]
I think the latter option is the best short term option (and has the least risk).  Let's not expose features that aren't ready for end users, even off by default.  We'll get Top Stories to more of them early next year.

**Comment by Mardak** [comment]
To avoid a new cycle of translations, we'll go with hiding the preference section if pocket would have been off by default (currently anything not en-US/en-CA).

**Comment by Mardak** [comment]
Fixed in #3002.
