### ISSUE TITLE
Migrate test pilot users to system-addon

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3112]
We need to update test pilot add-on to have it uninstall itself unconditionally for all firefox versions.

At the same time we can just flip the `browser.newtabpage.activity-stream.enabled` to true.

Sounds like messaging has already been told to Test Pilot users that it has been graduated, so we can just do stuff.

**Comment by Mardak** [comment]
We might also want to have nightly uninstall the add-on in case users can't update the add-on

**Comment by Mardak** [comment]
In particular sdk addons only get their `main` run when enabled. Whereas plain `bootstrap` add-ons can detect when it's installed but not started up. Probably good enough to just have the people who have the add-on still enabled migrated and leave the add-on cleanup in m-c for now. ?

**Comment by ncloudioj** [comment]
Yep, let nightly uninstall the addon is perhaps the better way. My PR won't work for 57 nightly users because it automatically disables the sdk addons.

I thought we could migrate most of the users based on the telemetry (attached below), i.e. the vast majority of addon users are still on release. So a self-destruct upgrade should be good enough here. 

```
 version  | count
-------- +-------
 54.0      |  4821
 55.0      |  1153
 52.0      |   219
 56.0      |   174
 53.0      |    75
 48.0      |    42
 51.0      |    31
 50.0      |    29
 49.0      |    21
 47.0      |    18
 45.0      |     7
 46.0      |     5
 42.0      |     3
 57.0      |     3
```
