### ISSUE TITLE
Top Sites and Highlights can't be removed from history if they are also bookmarked

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3254]
[Affected versions]:
- Firefox 57.0a1 Build ID 	20170827100428

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Visit a website and bookmark it.
3. Restart the browser and open a New Tab.
4. Remove the website from Step 2 from history using the context menu.
5. Observe the behavior.
 
[Expected results]:
- The website is removed from Top Sites.

[Actual results]:
- The website is not removed from Top Sites.

[Notes]:
- Attached a screen recording of the issue:
![top sites can t be removed if they are bookmarked](https://user-images.githubusercontent.com/18304511/29779035-01dd3b9c-8c1a-11e7-92f2-b2fd7f96b889.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
It seems Highlights are also affected by this behavior. As long as they are Bookmarked, they can't be removed from History.

**Comment by sarracini** [comment]
This is actually working as intended. When you delete something from your history that you've bookmarked, it doesn't delete the actual bookmark. So it's entirely possible that it comes up in your top sites/highlights, since we join on bookmarks. This becomes a design question - should we either 
1. not show bookmarks in top sites
2. when deleting from history, leave the bookmark but add the attempted "deleted" entry to the block list so it doesn't show in top sites but will still be a bookmark
3. actually delete the bookmark then actually delete the entry from history, removing it from top sites

@aaronrbenson @bryanbell

**Comment by sarracini** [comment]
We picked option 2
