### ISSUE TITLE
Only default sites shown after importing from another browser

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3266]
@Softvision-VladBacia says imported sites only appear after 15 minutes. If so, that makes it sound like the initial top sites query happens before import and saves that until the 15 minute timer.

**Comment by Mardak** [comment]
@Softvision-VladBacia can you reproduce this now on latest nightly? User testing videos seemed to show the opposite with top sites showing but no screenshots.

**Comment by SoftVision-CiprianMuresan** [comment]
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID 20170830220349

I tested the issue on the latest Nightly and Top Sites are not populated after the import is done.
![top sites not populated after import](https://user-images.githubusercontent.com/18304511/29923007-93cd2eb6-8e60-11e7-96e0-91a02c0a50c2.gif)

The issue is also reproducible if you use Sync.
![top sites not populated after sync](https://user-images.githubusercontent.com/18304511/29924938-5f0a03fa-8e67-11e7-8e93-1bc67441ff11.gif)

In both cases Top Sites are populated after a restart or after 15 minutes have passed.

Lastly, the issue is also reproducible on Mac OS.

**Comment by Mardak** [comment]
OH! Ha ha. *That* import button that we put right in front of users. I believe we already watch for import wizard completeto hide the message, so we can use that to refresh top sites.

Now that I think more about the user testing videos, I believe those weren't actually imports and were old browsing profiles or imported from before running Firefox (via installer)?

**Comment by Mardak** [comment]
"It would be really great if folks started to see their things on new tab as soon after the importer tool ran as possible. :slightly_smiling_face:
