### ISSUE TITLE
Request: I want to be able to undo removing an item

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#333]
(via @leibovic on IRC)

> 3:11 PM \<oyiptong\> margaret: removing an item deletes it from history right now
> 3:12 PM \<oyiptong\> Handle with care!
> 3:12 PM \<margaret\> heh
> 3:12 PM \<margaret\> luckily I’m not too protective of my data, I’m a good beta tester
> 3:12 PM \<oyiptong\> Heh
> 3:17 PM \<oyiptong\> margaret: if you feel we should block instead of delete, we can start a discussion on github
> 3:18 PM \<margaret\> oyiptong: I think deleting from history is fine, and a lot simpler to maintain
> 3:18 PM \<margaret\> we’ve had long discussions about this with regards to behavior for top sites on android
> 3:18 PM \<margaret\> I think we decided we just remove the site from everywhere if you’re removing it
> 3:19 PM \<oyiptong\> Indeed, we got to the same conclusion
> 3:19 PM \<oyiptong\> About deleting
> 3:19 PM \<margaret\> it just seems like a potential ux issue that you could accidentally hit that “x" too easily

**Comment by Soche89** [comment]
Just an opinion regarding this. Maybe we should take in consideration that some people wouldn't like to see a specific website in "Top Sites" area, but want to keep the history related to that site.
 If the user decides to remove a website from "Top Sites" area, will delete / block the entire history about that website. In this case the "Undo" functionality won't help the user to filter what websites are displayed in "Top Sites" area since they will reappear there.
If the user want's to remove also the history, he should have a block option for that site separately from "Top Sites" remove option.

**Comment by sarracini** [comment]
This is being tracked on Trello now https://trello.com/c/qb7h1qx3/36-i-want-to-be-able-to-undo-delete-and-dismiss-actions
