### ISSUE TITLE
Turn off Pocket stories if extensions.pocket.enabled = false

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3339]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1396336

I would guess this is in addition to checking the existing activity stream topstories pref?

**Comment by csadilek** [comment]
This was reported not so long ago and we decided not to fix it: https://github.com/mozilla/activity-stream/issues/3116

I would still argue that ```extensions.pocket.enabled``` controls a different distinct feature set. So, it should be independent of recommendations i.e. it makes sense to remove "Save To Pocket" from recs if pocket is disabled (which we recently fixed), but it's not ideal to remove recs altogether.

**Comment by Mardak** [comment]
Thanks. Duping to #3116 and replying with the same comment from that issue to the bug.

**Comment by zbraniecki** [comment]
@csadilek in my experience (I'm staying quite active on reddit/r/firefox, hackernews etc.) our Nightly community uses the `extensions.pocket.enabled` exclusively as a mean to turn off Pocket in Firefox. Their perspective does not involve a separation you described. They just decided they don't want Pocket.

While I understand that you want to preserve functional separation, may I ask if it would be possible to add a config flag that would cover both at once (`firefox.pocket.enabled` maybe)?

**Comment by csadilek** [comment]
@zbraniecki Thanks for sharing another perspective. It's not my call though. We can/should reopen and get product feedback. Do we know why some users set ```extension.pocket.enabled``` to false or what specifically they don't not like about the pocket integration? Wouldn't stories/recs  help attract new users that previously deactivated Pocket?

The stories component in Activity Stream is independent of Pocket and can be configured to show content from other providers. This technical separation can be addressed, but it just didn't seem intuitive to me that turning off the Pocket extension also turns off content recommendations in NewTab. Of course, I might be wrong about this. If I am, I think re-using the pref is better than introducing yet another one.

**Comment by zbraniecki** [comment]
> Do we know why some users set extension.pocket.enabled to false or what specifically they don't not like about the pocket integration?

I can only try to extract meaning from behind what those users are saying and their general sentiment (I did not run any studies).
The two primary motifs are:

 * The user is not interested in the browser providing him with data. They see Pocket as an extension that they don't want and are looking for ways to turn it off.
 * The user is surprised to see a new brand name in the product they downloaded. It triggers a lot of emotional response they have from tons of bundleware that secretly adds unwanted software/toolbar/buttons. They see Pocket as "bundled" with Firefox, and since they only wanted to install Firefox, they're looking for ways to remove the Pocket app.

I believe that the former is more meaningful in the long term, but the latter is more impactful in the context of 57 release.
What I mean by this is that in the long run, Pocket provides functionality that not all users may be interested in. It's not about the location (toolbar button vs new tab space). It's about the feature set. Ability to opt out of the UI that adds specific new type of data to your browser (beside history, downloads, search engine results) seems like a sensible and hopefully not hard way to address their needs.

But in the context of 57, I must say that the prominent branding of Pocket seems to have a high impact on the first run experience from new users. They don't know about that Pocket is part of Mozilla now, they just see another brand as part of Firefox and flag Pocket as bundleware that was sneaked onto them by Firefox. That I believe negatively affects both brands in the eyes of those users.
The idea that it's "hard to turn it off" is unfortunately playing into their labeling because most of real bundleware (think, toolbars installed when you install avast or sth like that) is hard to remove on purpose.
Being able to turn off Pocket, say from Preferences, in 57, would imho significantly mitigate the negative sentiment that's been growing.

I expect that in the long run, we'll be looking into more ways (that's what I heard from UX and Pocket teams) to blend the experience of using Firefox and Pocket and I expect that eventually they'll become a unified experience. But since at this moment it does feel like the functionality provided by Pocket fits the experience of installing an extension, users who're actively seeking for ways to configure the browser to their needs and decide to not use Pocket, would benefit from an option to do so, even if it's just an about:config flag.

Hope that helps!
