### ISSUE TITLE
Editing a Top Site URL wrongly creates a new Top Site

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3347]
https://bugzilla.mozilla.org/show_bug.cgi?id=1396835

[Affected versions]:
- Firefox 57.0a1 Build ID 20170904220027

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Click the "Edit" button from the Top Sites section.
3. Click the "Pencil" for one of the Top Sites.
4. Edit the URL and save.
5. Hover the previously edited Top site and observe the URL.

[Expected results]:
- The Top Site URL was edited.

[Actual results]:
- The Top Site URL was not edited and a new Top Site with the edited URL is created.

[Notes]:
- If you create two Top Sites in this way, when you dismiss one of them, both will be removed,
- Attached a screen recording of the issue:
![editing a top site url wrongly creates a new top site](https://user-images.githubusercontent.com/18304511/30063998-26ba5612-9259-11e7-9f63-af44ddcf4812.gif)

**Comment by piatra** [comment]
The issue [is here](https://github.com/mozilla/activity-stream/blob/master/system-addon/lib/TopSitesFeed.jsm#L127) when doing `Object.assign` the lookup is done using the url.

**Comment by piatra** [comment]
@aaronrbenson one part of the bug is clear, you shouldn't get 2 topsites when editing 1. But changing the URL is confusing.
1. If you change the TLD it's a completely new website 
2. You could type in a completely new URL 
What should happen here.

**Comment by aaronrbenson** [comment]
Yeah, this is wrong. The idea is you could completely take over a Top Site and turn it into something else. It's another way of performing an "Add" function.

**Comment by piatra** [comment]
@aaron there are still some things that are not clear.
Editing frecent website A to website B means we get a pinned site B in the position of A. Does this mean we should never show A again (because the user changed it to B)?
Initially what will happen is that B will take over A's position (and hide it) but frecent websites move around and A could show up again in a different position.

**Comment by piatra** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/810040/30164631-d005e492-93e5-11e7-90dd-39c3023a0f3e.png">
I edited "facebook" default site to have "twitter" url. Now I have only 5 defaults because the twitter default is removed (because of deduping) and facebook is not showing up because the pinned site in the second position has taken over.
Similar scenarios can happen with frecent websites.

**Comment by Mardak** [comment]
I wonder if the behavior should be that editing a top site is "Unpin existing if pinned" + "Pin new". This would still end up adding a new site to the position of the edit and pushing right an unpinned item (a frecent or default site), but at least avoids the editing a pinned site resulting in this current issue.

I would think making edit implicitly Block is more dangerous given that we have no way to unblock right now. And if the user really doesn't want the original item showing up any more, there's the option to block it.

Definitely something for design to chime in on.

**Comment by aaronrbenson** [comment]
Yeah, @Mardak has the right idea here.

**Comment by Mardak** [comment]
Sounds like this wasn't actually fixed? https://bugzilla.mozilla.org/show_bug.cgi?id=1396835#c2

**Comment by piatra** [comment]
@Mardak @SoftVision-CiprianMuresan I think we need to clarify the intent here. "Unpin existing if pinned" + "Pin new" as we discussed for the solution will still create 2 Topsites, by the original issue description it still reproduces but this is actually the behavior intended. 
Now with this patch the old website (the one that was edited) gets unpinned and this means it can naturally disappear out of Topsites. Before it would just remain pinned.

**Comment by Mardak** [comment]
Looking at the video from the first comment, it doesn't seem like the "extra" top sites are pinned.

**Comment by piatra** [comment]
Looked into this, and taking https://github.com/mozilla/activity-stream/issues/3347#issuecomment-327797154 into account, the only part that remains open about the bug is:

> If you create two Top Sites in this way, when you dismiss one of them, both will be removed,

This only happens if you test with a website that is not in your topsites (you add a new topsite and immediately edit it).

What actually happens is:
1. You add `foo.com`.
2. You edit `foo.com` -> `foo.net` (this is now pinned).
3. You have both websites in your topsites.
3.1 You dismiss `foo.com` (unpinned site). `foo.com` will be removed, `foo.net` remains (is pinned).
3.2 You dismiss `foo.net` (pinned site). This triggers a `PLACES_LINK_BLOCKED` event that causes a `refresh` on Topsites. Because `refresh` gets Topsites [from NewTabUtils not from store.state](https://github.com/mozilla/activity-stream/blob/2fc82208c948826bb8942f93ccf3ada0ee2a5921/system-addon/lib/TopSitesFeed.jsm#L59) the other website (`foo.com`) which **was never in your topsites** is lost. In addition to that `foo.com` has no frecency so it is an additional step where it would get filtered out.

There is also an inconsistency. Calling [block](https://searchfox.org/mozilla-central/rev/184f0c7888dd6abb32235377693b7d1fc0b75ac1/toolkit/modules/NewTabUtils.jsm#556) unpins the link. Calling [pin](https://searchfox.org/mozilla-central/rev/184f0c7888dd6abb32235377693b7d1fc0b75ac1/toolkit/modules/NewTabUtils.jsm#411) does not `unblock` a link. Leads to some weird cases when testing this out.

Also important, the call to unpin the blocked website that my patch added is not needed, when edit is called it will trigger `NewTabUtils.pinnedLinks.pin(site, index);` with the same index as the old topsite which causes an overwrite. We should revert the change.

**Comment by Mardak** [comment]
If you manually added/pinned `foo.com` then changed it to `foo.net` then there should only be `foo.net` in top sites. If `foo.com` was a top frecent page, then changing it to `foo.net` would show `foo.net` pinned and `foo.com` in its natural available spot for being a frecent top site.

**Comment by Mardak** [comment]
I wonder if #3447 would make it simpler to fix this as then we could just have pinning/unpinning call `getLinksWithDefaults` without worrying about it querying Places. Maybe I'll just go fix that issue this weekend.

**Comment by Mardak** [comment]
@piatra I was working on #3447 and ran into complexity refactoring because of the calls to `_getPinnedWithData`, so just making pinning stuff call `refresh` fixes the problem here and makes it easier to imlpement #3447.
