### ISSUE TITLE
Alignment of context labels on cards is off

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3399]
The alignment of the context icon and labels are off by just a pixel or two. The fix seems to be setting the line-height of the label to 16px.

![context-label-fix](https://user-images.githubusercontent.com/139451/30241252-5ddfe280-9545-11e7-9faa-062e434bb262.png)

**Comment by Mardak** [comment]
The "type" icon is in the right spot, but its corresponding text is currently too high? Does this affect Pocket (they're using the same styling):

<img width="192" alt="image" src="https://user-images.githubusercontent.com/438537/30241681-20e9a83c-953d-11e7-867e-7368307e1fbf.png">

Here it is with 16px line height. Good?
<img width="194" alt="image" src="https://user-images.githubusercontent.com/438537/30241692-4d2591fe-953d-11e7-8833-5f54eb4b46b4.png">

**Comment by Mardak** [comment]
@aaronrbenson Turns out this was exactly the behavior **before** #3195 which was a followup to #3076.

Here's the change from that PR:
![vertical align](https://user-images.githubusercontent.com/7219526/29421029-c33c511a-8341-11e7-835d-f689b53fd0b5.png)

It was requested to move the "Trending" label higher: "Context string should be vertically centered with lightning bolt icon"

I wonder if it's just a visual trick where the lightning bolt's bottom is much skinnier than the top:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/438537/30241871-c1bb8caa-9540-11e7-8d7b-ebdeb971b4ed.png"> <- 16px line-height

**Comment by Mardak** [comment]
re: trending bolt
"I noticed that too! Yeah, I think we need to adjust that icon to be visually centered"
![pasted image at 2017_09_09 11_33 am](https://user-images.githubusercontent.com/438537/30242855-50203fb0-9553-11e7-96a1-5063863e4c9b.png)
1px vs 1.5px vs 2px shifted bolt
"2px looks good"
