### ISSUE TITLE
The Components object is deprecated. It will soon be removed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#3437]
Randomly spotted in today's Firefox Nightly Developer Console on New Tab page:

<img width="1440" alt="new_tab" src="https://user-images.githubusercontent.com/557895/30347992-b0af674a-97c2-11e7-9649-0fc1809a5961.png">

**Comment by k88hudson** [comment]
Yeah, this happens unfortunately even in a `typeof` check :'(

**Comment by underrated** [comment]
Will it actually be removed or preserved for backward compatibility? Can anyone estimate when it will be removed? I use TiddlyWiki classic to store personal notes locally(no server) and it only seems to work on Firefox but I see that warning. I would really like to know when I could expect it to break so that i make some changes to the js code inside the tiddlywiki html file.
