### ISSUE TITLE
Search arrow does not respond to clicks after a Top Site or Highlight is dropped in the Search Bar

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3444]
https://bugzilla.mozilla.org/show_bug.cgi?id=1399397

[Affected versions]:
- Firefox 57.0a1 Build ID 20170904220027

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Drag a Top Site in the Search bar.
3. Click the "Search" arrow and observe the behavior.

[Expected results]:
- The search is performed with the default search engine.

[Actual results]:
- The search is not started.

[Notes]:
- The issue is also reproducible if you drag a Pocket card or a Highlight card.
- The issue is not reproducible if you press Enter after following the steps.
- Attached a screen recording of the issue:
![search button not working after a top site is dropped in it](https://user-images.githubusercontent.com/18304511/30370805-57209220-9881-11e7-99e0-1c3f97872c55.gif)

**Comment by AdamHillier** [comment]
I believe this is actually an issue with contentSearchUI. When you drag a site in and click the arrow, [this line](http://searchfox.org/mozilla-central/source/browser/base/content/contentSearchUI.js#249) throws because `event.originalTarget` is undefined. Even in a normal search `event.originalTarget` is undefined but it doesn't get executed because [`contentSearchUI._table.hidden`](http://searchfox.org/mozilla-central/source/browser/base/content/contentSearchUI.js#248) is true for normal searches, and false when you drag-then-search. It would be a simple fix in contentSearchUI, or we can just do

```js
if (!event.originalTarget) {
  event.originalTarget = {}
};
window.gContentSearchController.search(event);
```
@Mardak?

**Comment by Mardak** [comment]
So.. the odd thing is that dragging into existing about:home (e.g. from the snippet link) searches correctly...

And it looks to do the same thing:
https://searchfox.org/mozilla-central/source/browser/base/content/abouthome/aboutHome.js#212-213
```html
        <input id="searchSubmit" type="button" onclick="onSearchSubmit(event)"
```
```js
function onSearchSubmit(aEvent) {
  gContentSearchController.search(aEvent);
```

**Comment by Mardak** [comment]
Let's fix it in m-c attach patch to https://bugzilla.mozilla.org/show_bug.cgi?id=1399397

**Comment by AdamHillier** [comment]
Yeah that is weird - I just checked and about:home sets the originalTarget. Anyway, I'll do it, who should I ask to review?

**Comment by Mardak** [comment]
If it's just that one line change, r?me is fine. Or ursula

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/dc6acc3b9707
