### ISSUE TITLE
Add telemetry for prerendered or not

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3498]
We can already detect preloading based on some timing numbers but that's covered in #3144. Prerendering probably will have impact on various metrics, so it would be good to be able to differentiate

**Comment by ncloudioj** [comment]
Looks like we also wanted to record "if the browser started preloaded" in #3144. In order to make this more flexible, I'd propose to capture those options in an encoded integer, i.e. add a field `load_mode` in the telemetry, which could be any one or bitwise-or'd combination of following values,
```js
{
  "none": 0,
  "preloaded": 1 << 0,
  "prerendered": 1 << 1,
  ...
  "other optimizations": 1 << N
}
```
Did we just want to add this to the `perf` object of the `session` ping? Or make it available to other pings as well? @emtwo @Mardak @dmose
