### ISSUE TITLE
Add telemetry for search placeholder first painted

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3499]
This is to match the quantum hero element tracking

**Comment by ncloudioj** [comment]
As we're looking to calculate the "search_first_paint_ts" inside of "componentDidMount", @k88hudson pointed out that this would be tricky to measure if it's prerendered. Fortunately, we have a `is_prerendered` flag in the `session.perf`, which could help us filter out those prerendered measures in the performance analysis.

**Comment by dmose** [comment]
There are ways to do this sort of thing, but if we're hoping to match the quantum metric, we would ideally measure it in the same way that Quantum does, which is when the search placeholder text appears.  Since that depends on locale strings, does that mean the placeholder won't actually be rendered until the client-side React code attaches?

Somewhat separately from that, it would be interesting to know how the search placeholder text rendered is noticed in the Quantum benchmark.  Perhaps @digitarald or @mconley knows?

**Comment by dmose** [comment]
So maybe this is really `search_first_placeholder_paint_ts`.

**Comment by ncloudioj** [comment]
Wonder if https://github.com/mozilla/activity-stream/pull/3740 is related to this.

**Comment by Mardak** [comment]
If we're looking to measure first paint of placeholders, doing it from react is probably not that correct. The prerendered placeholder content should appear before javascript finishes execution (i.e., before Search `componentDidMount`). With #3740, there should be no distinction between the box appearing and text appearing, so probably not worth the effort to instrument strings coming in especially if we fix #3741.

**Comment by ncloudioj** [comment]
We'll revisit this once we know more details about how Quantum measures the hero element first painted.

**Comment by dmose** [comment]
Turns out this is currently done once weekly, stepping through screen capture frames on the reference hardware with the screen capture dongle, by hand.

**Comment by dmose** [comment]
Which has some non-trivial margin of error, if I understood @onkeltom correctly.
