### ISSUE TITLE
Empty pocket stories and no topics on error

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3501]
Had this in console: `Failed to fetch content: NetworkError when attempting to fetch resource.  TopStoriesFeed.jsm:83`

Page looked like this:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/438537/30504047-89eda7c8-9a21-11e7-868a-10a63d5b050e.png">

Refreshing and additional new tabs kept the empty cards.

Network seems to be fine as I can load pages or the highlights that are now pushed down below these empty cards. Restarting fixes.

**Comment by csadilek** [comment]
This should only happen if the very first fetch fails (after starting the browser) as otherwise the previously loaded stories should be displayed.

Currently, we don't retry until the next system tick (5 minutes). We're already observing the NEW_TAB_REHYDRATED event though so we could use that and retry if we haven't yet successfully fetched stories?

**Comment by Mardak** [comment]
Wontfix as this is less of an issue now that we have caching from #3606

**Comment by Mardak** [comment]
Potentially we could be smarter when network comes back to request again.
