### ISSUE TITLE
Add recent downloads to Highlights

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3535]
Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1354536 is reusing Activity Stream's Highlights queries to populate "Recent Activity" feature in the Library panel. The bug was originally filed as including downloaded items.

As we currently don't have downloads in Highlights, neither feature shows downloads.

**Comment by aaronrbenson** [comment]
Relates to: https://github.com/mozilla/activity-stream/issues/3155 since we'd want to have settings to let people turn off/on seeing Downloads as Highlights.

**Comment by piatra** [comment]
What would clicking a "Downloads" highlight card do?

**Comment by aaronrbenson** [comment]
@piatra When you click on the highlight card for a download, it would open the file. It should work just like the downloads panel in the Library.

**Comment by piatra** [comment]
@sarracini can we do that ^ given the privacy settings on about:home/newtab?

**Comment by Mardak** [comment]
If we can't open from the content page, it could open it from chrome.

**Comment by sarracini** [comment]
Yeah, showing your downloads will probably require some level of privileges that the content page doesn't have. As Ed said, it would have to open it from chrome. ```about:downloads``` doesn't run in the content process and has system principal privileges since it has to look up paths on your file system, so I assume showing some content from about:downloads will also require the same security settings.

In terms of privacy, it might need to go through a privacy review... showing your downloads on your newtab page sounds like it may have privacy concerns so I imagine it'll need a privacy review

**Comment by dmose** [comment]
It's at least plausible (though unclear how practical), that we could design a tightly restricted API surface that would just send through the data we need from more privileged code, perhaps even via our current state-sharing mechanism with chrome via messages (or maybe indexeddb?).

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1433230
