### ISSUE TITLE
Intermittent browser_newtab_overrides.js | leaked 2 window(s) contentAreaDownloadsView.xul

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3578]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1399854

Might be related to touching aboutNewTabService for #3396

**Comment by sarracini** [comment]
The easiest way to fix this is to change the test to use literally any other chrome url than ```contentAreaDownloadsView.xul``` since I've managed to track down the leak coming from somewhere in this thing: https://dxr.mozilla.org/mozilla-central/rev/083a9c84fbd09a6ff9bfecabbf773650842fe1c0/browser/components/downloads/content/allDownloadsViewOverlay.js#211.

I've tested out with different chome URLs and the leak goes away: 
https://treeherder.mozilla.org/#/jobs?repo=try&revision=68c60871314c158e8810f9d08d1ac86bf9f5eb92&group_state=expanded

I've also tested it without the initialization of ```DownloadsPlacesView``` constructor and the leak also goes away:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=dbc02dacce2682becb8f84265e968ff341e0a3b1&group_state=expanded

I've tested it in loads of other cases, most recently trying to comment out different parts of the ```DownloadsPlacesView``` constructor:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=30b9d531904f663a17bb3deb181b26b20b989c10&group_state=expanded

The leak seems to go away with those parts commented out. At this point, I think it's out of scope for this ticket to track down a leak in ```allDownloadsViewOverlay.js``` when we can easily fix the issue by using any other chrome url for this test. 

This test is the *only* test in m-c that's opening and closing tabs with ```contentAreaDownloadsView.xul``` as the url, so if something in this file started leaking for some reason, this test would be the only one that would expose that. 

@Mardak what do you think? Should we just change the test url to point to something else?

If you're curious to see my adventures trying to chase this leak down you can see all the try builds scattered here: https://treeherder.mozilla.org/#/jobs?repo=try&author=usarracini@mozilla.com to see what things I've tried which lead me to this conclusion

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/f4c0f4165f13
