### ISSUE TITLE
Removing a bookmarked Highlight comes back as Bookmarked but it's not actually

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3587]
Looks like the links cache is too aggressive in its caching. Probably need to expire the cache on `case at.PLACES_BOOKMARK_REMOVED:` although the current logic to expire is when `this.fetchHighlights(true);` So probably just need to be smarter all around on when to expire the cache or not. Or when to broadcast or not.

**Comment by piatra** [comment]
The pull request I landed https://github.com/mozilla/activity-stream/pull/3623 [adds a `linksCache` refresh on BOOKMARK_REMOVED](https://github.com/mozilla/activity-stream/blob/bdf3f3adcc44798c73a38a944cd1a6612b2baf56/system-addon/lib/HighlightsFeed.jsm#L192) because I ran into the same behavior. Do we want to close this issue and maybe file another if there are still improvements we can add to the `linksCache`?
