### ISSUE TITLE
[Enhancement] Collapsed sections should be animated when they are reopened

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3677]
https://bugzilla.mozilla.org/show_bug.cgi?id=1407228

[Affected versions]:
- Firefox 58.0a1 Build ID 20171009220104

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Collapse the Top Sites section.
3. Reopen the section and observe the behavior.

[Expected results]:
- The Top Sites section is animated as it appears.

[Actual results]:
- The Top Sites section appears instantly.

[Notes]:
- Because we have an animation when collapsing sections, it really feels incomplete to not have a similar animation when reopening the sections.
- The issue is also reproducible for the "Recommended by Pocket" and "Highlights" sections.
- Attached a screen recording of the issue:
![reopening collapsed sections](https://user-images.githubusercontent.com/18304511/31388861-14d4fef8-add8-11e7-9b4c-b808b1561e4e.gif)

**Comment by Mardak** [comment]
It is animating but at a different speed especially for those with only 1 row. See screenshot of the above recording:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/438537/31391942-cf07f59c-ad8c-11e7-8716-215c5613a3dc.png">

In particular, the 3rd row is still not visible.

This is caused by animating to/from a fixed 900px max-height instead of the actual height of the section.

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/699b253725efc849c4587b8c961f65f3e97d0bce
