### ISSUE TITLE
A Pocket recommendation which is also a Top Site is wrongly redisplayed after a restart

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/activity-stream#3678]
https://bugzilla.mozilla.org/show_bug.cgi?id=1407232

**[Notes]:**
- If you dismiss the "Pocket" recommended website, the website is also dismissed from the Top Site area and vice versa.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile.
- Change the "browser.search.region" pref to "US".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and open a new tab.
2. Open a recommended by Pocket website multiple times.
3. Dismiss a Top Site and observe the "Recommended by Pocket" area.
4. Restart the browser.
5. Observe the "Recommended by Pocket" area.

**[Expected result]:**
Step 3: The website is no longer displayed in the "Recommended by Pocket" area.
Step 5: The website is no longer displayed in the "Recommended by Pocket" area.

**[Actual result]:**
Step 3: The website is no longer displayed in the "Recommended by Pocket" area.
Step 5: The website is redisplayed in the "Recommended by Pocket" area.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/31389497-d71d3b0a-add9-11e7-9ec4-b1d2d597e9a3.gif)

**Comment by bryanbell** [comment]
So the bug is that we seem to be de-duplicating the page as soon as a Pocket Recommended page makes it to "Top Sites" and for some reason, that de-duplication doesn't persist after a restart. Weird. 

![screen recording 2017-10-25 at 03 16 pm](https://user-images.githubusercontent.com/228979/32026412-2e2809aa-b999-11e7-89e1-e9698a9fac4c.gif)

The reason I'm inclined not to fix it at this time, and why it can wait, is that this can only happen on a blank profile, and if a user jumps right in and opens a page multiple times, and then dismisses an existing Top Site, then restarts. The likelihood of a user running into this issues is very slight. By its nature, the algorithm that governs Top Sites would make it impossible for a user to run into this problem with just a couple days of use since it prefers all-time most visited sites, and resists recent reads.

**Comment by tspurway** [comment]
closed - intended
