### ISSUE TITLE
Problematic code in "init-store.js"

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#3725]
Came across this bug while implementing #3455 , looks like [adding properties to store](https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/lib/init-store.js#L93-L94) won't work as expected for redux middlewares. See more details [here](https://github.com/reactjs/redux/blob/b30e6ae4aa217766dbc8bb0d5b9eb87f6c5c8bbd/src/applyMiddleware.js#L19).

It didn't break the code due to the coincidence that 
```js
store._didRehydrate = false;
store._didRequestInitialState = false;
```
has the same effect as
```js
store._didRehydrate = undefined;
store._didRequestInitialState = undefined;
```

We should fix this to avoid further bugs in the future.

**Comment by Mardak** [comment]
Following from @k88hudson's explanation https://github.com/mozilla/activity-stream/pull/3731#issuecomment-337637292

Here's the code that's causing the `createStore` to have a different store than what middlewares see:
https://github.com/reactjs/redux/blob/fdfd13fbc83f2843bd6420c48b9b39d5fa17113d/src/applyMiddleware.js#L21-L29
(I know that links to a different version from what we're using, but it has the same concept.)

`applyMiddleware` returns a copy of the store created (which is what ends up getting returned by `createStore`) whereas the middlewares use a shared `middlewareAPI` wrapper store that has store-like properties.

Maybe instead of attaching properties to the store object, the state should be updated somehow, and the middleware should be doing `store.getState()` to change its behavior?

E.g., initialState should have somewhere:
```js
{
  didRehydrate: false,
  earlyMessageQueue: []
  …
}
```

?

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1425498
