### ISSUE TITLE
A top site can also be displayed in the Highlights section

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla/activity-stream#3729]
https://bugzilla.mozilla.org/show_bug.cgi?id=1409715

[Affected versions]:
- 58.0a1 (2017-10-17)
- 57.0b9 (20171016185129)

[Affected platforms]:
- Windows 10 x64
- macOS 10.12.1
- Ubuntu 14.04 x86

[Steps to reproduce]:
1. Launch Firefox using a clean profile.
2. Open multiple times a random website (that is not a top site)
3. Dismiss a random top site

[Expected result]:
- [step 2] The chosen website is shown in the Highlights section
- [step 3] When the chosen website becomes a top site, it is also removed from the Highlights section

[Actual result]:
- [step 2] The chosen website is shown in the Highlights section
- [step 3] The chosen website is shown in both Top Sites and Highlights sections (see the screencast https://goo.gl/wVPRSY)

[Regression range]:
- This is not a regression, as it's reproducible all the way back to 57.0a1 (2017-09-08) build, when the Highlights section was introduced (bug 1396609)

**Comment by Mardak** [comment]
I noticed that HighlightsFeed typically runs before TopSitesFeed on various actions. So in this case, I believe this is because TopSites doesn't have imdb yet, and by the time it does -> TOP_SITES_UPDATED, Highlights doesn't broadcast the deduped imdb removal.

**Comment by Mardak** [comment]
Seems like one approach to fix this is to have HighlightsFeed remember that it needs to broadcast the next TOP_SITES_UPDATED from a BLOCKED action but not actually fetch until TopSites is ready to dedupe correctly.

**Comment by bryanbell** [comment]
I see zero issue with this behavior. We're talking about a clean profile here. If that user has only gone to one site, then surely that site should be a Top Site, and it's also a highlight of their experience. 

There's no rule that if a site is a top site it can't be a highlight, and the rare redundant item is acceptable, especially in a situation where not enough data exists.

**Comment by IuliaCristescu4** [comment]
The clean profile scenario was chosen in order to be easy to understand (reproduce) and to eliminate as many variables as possible. This issue is also reproducible using a dirty profile (e.g. history composed of hundreds of visited sites).

**Comment by bryanbell** [comment]
So my lack of total concern in regards to an item showing as a Highlight and a Top Site is based on how Top Sites and Highlights work.  Top sites look for websites that the user consistently goes to over an extended period.  Top sites also favor top-level-domains over other internal pages.  The Highlights algorithm, on the other hand, has a very short horizon of activity to look at, typically three days. So if a user sees a duplicate item as a topsite, and a highlight then it's come to honestly. That is because the user has only been using the software a short time, and so their top site and a highlight could be one in the same. The mission of the New tab is to get users back to things that they thought were interesting, and given this user's limited usage the item that is picked up by the Top Sites and Highlights Algorithm is probably the best option to return to that user. Top Sites and Highlights also display content in entirely different ways, so jogging a users recognition of a resource is better. News sites show the same story in a couple of different ways on their home pages so different users might recognize a given story as attractive to them, and I think of this in the same way. We have a user with limited usage history over a short period. So our choices are limited to what we can show them, so over serving particular sites that they've engaged with isn't necessarily a bug.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1409715
