### ISSUE TITLE
Generate smaller manifests (e.g., combined urls, no title / url protocol)

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3847]
Looks like some google properties are using the same image_url (although each region has its own google.com.* icon url):

   8 https://www.google.com/images/branding/product_ios/3x/gsa_ios_60dp.png
   6 https://ir.ebaystatic.com/pictures/aw/pics/mobile/images/apple-touch-icon.png

https://activity-stream-icons.services.mozilla.com/nightly/icons.json.br

Also, unclear what the title value will be used for ? And the client strips out the protocol anyway.

But also unclear how much of an effort / benefit this is.

**Comment by Mardak** [comment]
Also, a protocol-less url -> domain would probably require an endpoint version bump.

**Comment by rlr** [comment]
We got everything fixed except for the google case which is a little more complicated because of the TLD differences in the icon URL. I think it's good enough for now.

https://activity-stream-icons.services.mozilla.com/v1/icons.json.br

**Comment by Mardak** [comment]
I was just checking out the new json, and my own browsing history doesn't seem like tippy top will do much, so it'll be interesting to see the icon stats.

Of my top 30 top sites, 12 already have rich icons. And of the 18 that don't have rich icons, only the "google" top site has a "better" tippy top icon. The google page is https://www.google.com/flights/ and that has its own custom icon https://www.google.com/flights/static/favicon.ico so replacing it with a rich google icon could make it look nicer but might be confusing.

**Comment by Mardak** [comment]
If anyone wants to check for their own top sites, copy/paste into Browser Console:
```js
(async numItems => {
  tippy = new Set((await (await fetch("https://activity-stream-icons.services.mozilla.com/v1/icons.json.br")).json()).reduce((acc, {domains}) => [...acc, ...domains], []));
  console.log((await NewTabUtils.activityStreamLinks.getTopSites({numItems})).filter(({faviconSize, url}) => !(faviconSize >= 96) && tippy.has(new URL(url).hostname.replace(/^www\./, ""))).map(({url}) => url));
})(30)
```

Where the 30 on the last line is to check the first 30 top sites

**Comment by rlr** [comment]
> If anyone wants to check for their own top sites...

For me tippy top helps 4 from the top 30. The interesting ones were weather.com and bankofamerica.com. There was also facebook but we already ship a tippy top icon for that and the other was some google url.

I assume you ran this before the favicon feed actually ran? Because once it ran for me, then the ones from tippy showed up as rich icons 😄 

Some sites from my top sites that dont have rich or tippy top but probably should: cnn.com, mint.com, quora.com, fidelity.com. We should probably spend some time looking into making the manifest cover more of these cases. I wonder if we are going to have to end up doing some manual curation.

Also wonder if lowering the resolution limit might help? For example, cnn has a 76px icon so we show a screenshot. But maybe the slightly lower than 96px icon is better?
<img width="251" alt="screen shot 2017-11-19 at 8 19 00 pm" src="https://user-images.githubusercontent.com/36629/32998199-05e6eace-cd67-11e7-9d40-870708dff20e.png">

**Comment by Mardak** [comment]
Oh ha right. I suppose that code snippet isn't useful for those on a nightly that had updated. When I provided it, the nightly build with tippy top fetching hadn't been built yet. Here's some code to include top sites (of first 100) that have tippy top or would get tippy top:

```js
(async numItems => {
  tippy = new Set((await (await fetch("https://activity-stream-icons.services.mozilla.com/v1/icons.json.br")).json()).reduce((acc, {domains}) => [...acc, ...domains], []));
  console.log((await NewTabUtils.activityStreamLinks.getTopSites({numItems})).filter(({faviconRef, faviconSize, url}) => faviconRef || !(faviconSize >= 96) && tippy.has(new URL(url).hostname.replace(/^www\./, ""))).map(({url}) => url));
})(100)
```

Out of the top 100, I get google, twitch, yelp. There were a few others, but it was because I hadn't visited them since we landed rich icons (e.g., paypal) but those sites actually has their own apple-touch-icons.
