### ISSUE TITLE
Bug 1259095 - "See more activity" button is no longer displayed if all websites from Timeline viewport are removed 

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#451]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1259095

---

Created attachment 8733950 [details]
missing See more activity button.zip

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.4

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.4) was previously installed on a profile.
- Have more more history so that the "See more activity" button is displayed on Activity Stream Timeline page 

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Hover the mouse cursor over a website from "Just Now" area.
3. Click on "X" button to remove the website.
4. Remove all websites from viewport.

#### [Expected results]:
"See more activity" button is displayed so the user could display more visited websites from history. 

#### [Actual results]:
"See more activity" button is hidden.

**Comment by SoftVision-VladBacia** [comment]
The behaviour has changed due to implementation of infinite scrolling.

This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160630030207) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.
