### ISSUE TITLE
Bug 1262156 - Next videos played from YouTube don't show up in Timeline

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#470]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262156

---

Created attachment 8738141 [details]
Screencast of the issue.mp4

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a profile.

#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Go to YouTube.com, search for something and click on one of the resulting items 
4. Go back to "Activity Stream" timeline and refresh the page
5. Go back to the YouTube page and play other videos.
6. Repeat Step 4.

#### [Expected results]:
Each played videos from step 5 are displayed in the "Just Now" area from "Activity Stream" page

#### [Actual results]:
All the other videos except the first are not displayed in the "Just Now" area from "Activity Stream" page.

#### [Notes]:
-This issue is reproducible also in New Tab page.
-Reproducible 5/5 times.
-Attached a screen recording with the issue.

**Comment by ciprianmuresan** [comment]
There seems to be a more general issue here, where the items from History don't update properly in the Just Now area. After browsing several sites and articles or links from the sites I have a lot of links in History and less than that in the Just Now area. So it's not limited to YouTube links.

When this occurs, it also causes a strange behavior in Activity Stream, where you delete a link from Just Now or Highlights and because it is not properly deleted from History. After a refresh the previously deleted link infinitely reappears in the Just Now area or Highlights after each delete attempt. In order to stop them from reappearing, you must delete them individually from browser History.

**Comment by rlr** [comment]
There is a problem with youtube links because the deduplication logic throws away the query string. So all `https://www.youtube.com/watch?v=*` look the same and it will show only one. Seems like we need to create a special case to for some sites that have meaningful query params. @k88hudson thoughts?

**Comment by pdehaan** [comment]
@nchapman says this is likely a Firefox pushstate bug.

**Comment by SoftVision-VladBacia** [comment]
This issue was verified on latest Nightly 50.0a1 (Build ID: 20160608030219) with Activity Stream v1.0.19-dev and it cannot be reproduced.
