### ISSUE TITLE
Missing icons should fall back to the letter and color combination. 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#488]
<img width="769" alt="missingicons" src="https://cloud.githubusercontent.com/assets/228979/14390339/44a3a874-fd6b-11e5-89ed-591030f9dc60.png">

**Comment by pdehaan** [comment]
Ref: #449

**Comment by dmose** [comment]
This appears to me to be working correctly on master.

**Comment by k88hudson** [comment]
This is mostly already covered, except for two cases:

- the favicon is protocol-less (since there is no protocol for the activity stream, these won't work)
- the favicon link is broken; for this, it would be great to add a handler for an image load error event and then use the text/color fallback if that happens

Relevant code for the selector is here: https://github.com/mozilla/activity-stream/issues/488, and the component is here https://github.com/mozilla/activity-stream/blob/master/content-src/components/SiteIcon/SiteIcon.js. Tests are in `content-test/`

**Comment by k88hudson** [comment]
I'm going to mentor this one for a contributor

**Comment by Mardak** [comment]
Before: 
![screen shot 2016-07-28 at 1 57 43 am](https://cloud.githubusercontent.com/assets/438537/17206880/c7e515c2-5466-11e6-82f8-ab4768ad3282.png)


After: 
![screen shot 2016-07-28 at 1 56 13 am](https://cloud.githubusercontent.com/assets/438537/17206884/cbd23d86-5466-11e6-9048-ce671d0e7450.png)

**Comment by Mardak** [comment]
Builds on top of the fix for #944 with commit https://github.com/Mardak/activity-stream/commit/89ff7f9718995cc0168d397190fb5a99524ff700
