### ISSUE TITLE
Collapsing / Grouping UI for sessions based on URL

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#609]
![pasted_image_5_1_16__6_57_pm](https://cloud.githubusercontent.com/assets/228979/14945893/9fd70072-0fce-11e6-8a70-952dc926b2b0.png)

KABOOM!

**Comment by pdehaan** [comment]
Odd, I was unable to reproduce this when going to google maps and searching and dragging the maps.

![new_tab](https://cloud.githubusercontent.com/assets/557895/14960662/92c65af0-104a-11e6-8a64-2abf17195b1f.png)

You can see in the screenshot above that results seem to usually be in pairs for me.
I went to maps.google.com, and it redirected me to google.com/maps and also added a result with an embedded lat-long in the query string. The later result with the lat-long was me dragging the map.
I'm guessing that's why your history imploded and folded into itself, you probably dragged the map around looking for something specific. It looks like your zoom level stayed the same though for each of the visits. Not sure how/if we could "fix" this. I'm guessing it's just a byproduct of Google rewriting the query string and Firefox considering those to be unique page views and stacking them in the browser history.

**Comment by callahad** [comment]
This absolutely repros on my end. I do have to stall long enough when dragging the map for the URL to be updated. It also produces an entry in the normal History sidebar.

**Comment by tspurway** [comment]
This is really about collapsing / grouping similar (same) sites.

**Comment by pdehaan** [comment]
Ref: #350

**Comment by sarracini** [comment]
Feature requests should be added to the trello board
