### ISSUE TITLE
'see more activity' is only displaying 1 item per click

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#638]
1. goto timeline view
2. click 'see more activity'

actual: only 1 item displays.  Methinks this is a regression.

expected: I should see ~5 or more display

**Comment by k88hudson** [comment]
I'm not able to reproduce this, is it possible you only have one more item in your history? Do you see this multiple times when you click 'see more activity'?

**Comment by edmoz** [comment]
hmm I only see ~ 10 items in 'today' and 100+ items in 'yesterday'.  But maybe there's a de-dupe problem as my history is full of gmail urls

<img width="883" alt="screen shot 2016-05-05 at 8 20 29 am" src="https://cloud.githubusercontent.com/assets/3698618/15047578/608f6e26-129a-11e6-806d-88ec855b8ab9.png">

**Comment by k88hudson** [comment]
We don't actually do any de-duping on the Timeline view, hmmm...

What version of the add-on are you on?

**Comment by k88hudson** [comment]
I will try to reproduce

**Comment by edmoz** [comment]
I'm on 1.0.14-dev on mac fx nightly.  I can do a vidyo if you want

**Comment by edmoz** [comment]
this only really happens with all my 100 gmail items, not with other history it seems.

**Comment by softvision-VladBacia** [comment]
I can reproduce this issue with Google Translate links. Translate a couple of words and after that access the Timeline to see how are they displayed. [Here](https://goo.gl/kR87Ga) is a video with this behavior.

**Comment by dholbert** [comment]
I'm hitting this as well. In my case, the "one at a time" entry is the same item, which is a Google Docs link. So, if I click "See more" over and over, I just get a bunch of copies of that same link at the bottom of my stream.

This particular URL might have been the first page that I loaded after enabling the Activity Stream experiment -- not sure.  (So it might be that we're hitting the "beginning of time" and stalling/repeating the oldest link over and over.)

**Comment by k88hudson** [comment]
Hm, it looks like this might be caused by the hash of a URL not being included in the deduplicating strategy, add-on side. I will investigate

**Comment by k88hudson** [comment]
Ok, so the issue here is that we deduplicating/returning results based on on our cacheKey, but not in our query. That means if we receive the following urls from our query:

```
https://foo.com#bar
https://foo.com#baz
https://foo.com?somerandomkey=blah
```

We will de-duplicate to a single entry, which will end up being the first one (`https://foo.com#bar`). That means although we might have received 25 results back from the query, we might end up deduplicating them to 1.

While doing this for the purposes of *caching* and receiving data from embedly makes sense, I don't think we should be doing any de-duplication on actual history items. We'll need to refactor the caching code a bit to allow for this.

**Comment by k88hudson** [comment]
This is now resolved!
