### ISSUE TITLE
"Delete from history" doesn't make sense for bookmarked items

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#640]
For items that are in highlights because they were bookmarked, or items in the Bookmarks tab of the Timeline, deleting either doesn't work at all or doesn't make much sense. Should we perhaps be deleting the bookmark instead and change the language?

**Comment by k88hudson** [comment]
cc @bryanbell

**Comment by SoftVision-PaulOiegas** [comment]
I think this may be a duplicate to our question in #584.

**Comment by rittme** [comment]
Issue 659 changed the language and now removes the bookmark.
But in the new tab and history pages the link show up again when the page is reloaded, because it's still in history.

I wonder if when the user clicks remove, he wants it to only not be a bookmark anymore or he wants it to be removed from the list altogether? What should be the appropriate behavior for removing bookmarks on the new tab and history pages?

**Comment by k88hudson** [comment]
This is resolved by the new context menu in #701; now there is different language for bookmarking/deleting
