### ISSUE TITLE
Bug 1271647 - The selected/click items from Activity Stream are surrounded by a dashed border

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#673]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1271647

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.15

[Affected Platforms]:
- All Windows
- All Linux

Prerequisites]:
- Latest Activity Stream add-on version (1.0.15) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Activity Stream button from the browser toolbar.
3. Click on "Bookmarks" button from Activity Stream sidebar.

[Expected result]:
- The "Bookmarks" button is focused with no UI issues.

[Actual result]:
- The "Bookmarks" button is focused but is surrounded by a dashed border.

[Notes]:
- If you press and hold the click on any item from Activity stream pages, the item will be surrounded by a dashed border. 
- This issue was present on earlier versions, but only when using scroll / middle click button.
- The issue is reproducible on the New Tab page as well.
- Issue is not reproducible on Mac OS platform.
- Attached a screen recording of the issue https://bug1271647.bmoattachments.org/attachment.cgi?id=8750795

**Comment by tspurway** [comment]
#677 reported as dupe

**Comment by SoftVision-CosminMuntean** [comment]
This issue was retested with Activity Stream v1.0.18 on latest Nightly (49.0a1) e10s disabled. It seems that with e10s disabled the issue is partially reproducible.

We noticed that, after the "Tab" button from keyboard is pressed to select items, the selected items are highlighted with the dotted border. The dotted border is still visible even if the items are selected with mouse click. After a refresh, the dotted border is no longer visible when items are selected with mouse click.

You can observe this behaviour [here](https://goo.gl/sojErs).

**Comment by sarracini** [comment]
@SoftVision-PaulOiegas can you still reproduce this?

**Comment by Softvision-VladBacia** [comment]
@sarracini , the steps have changed because the Timeline has been removed but the issue is still present in New Tab page. For the current steps you need to drag&drop a Highlight tile in order to display the selection area or right-click on the Highlight tile and press "Esc" key to dismiss the context menu.

![dashed border](https://cloud.githubusercontent.com/assets/9248513/19522845/42ef9f48-9621-11e6-8b21-414fbcfbe74f.gif)

**Comment by sarracini** [comment]
@Softvision-VladBacia i can't reproduce this anymore, can you?

**Comment by sarracini** [comment]
This was fixed

**Comment by Softvision-VladBacia** [comment]
This issue is no longer reproducible in Activity Stream Dev 1.3.0-dev-1484695187.
