### ISSUE TITLE
Bug 1271941 - Content is not automatically displayed for "Timeline" and "New Tab" pages when `remember windows and tabs from last time` option is set in `about:preferences`

### ISSUE THREAD

**Issue by SoftVision-VladBacia** [mozilla/activity-stream#674]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1271941
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.16

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Create a new profile.
- Install Activity Stream through Test Pilot.
- Browse a few links as a new user (50-100 visited websites, 1 bookmarked website).

[Steps to reproduce]:
1. Go to about:preferences->General and select "When Firefox starts: Show my windows and tabs from last time".
2. Click on "Activity Stream" button from browser toolbar.
3. Close all other tabs.
4. Close Firefox.
5. Start Firefox.

[Expected results]:
- Activity Stream Timeline content is automatically displayed with all items in viewport.

[Actual results]:
- For a few seconds the Mozilla start page is displayed and then it is replaced by Activity Stream Timeline. Activity Stream Timeline is empty although there is content in history. Even the Highlight tiles are hidden. Resource link is displayed in the browser address bar.
- If we visit the Bookmarks page from Activity Stream Timeline, we can see that this page is also empty (1 website is bookmarked).
- Content is displayed if the user performs a manual refresh of the page.

[Notes]:
- If we repeat the same scenario for New Tab page, we can observe that the loading spinner is displayed indefinitely with the message "Hang on tight! We are analyzing your history to personalize your experience", until the user refreshes the page.
- Videos are available [here](https://drive.google.com/open?id=0B6QogV2AJFKiSXNWUkpZdDdsMlk)

**Comment by rlr** [comment]
I've been unable to reproduce this on dev edition. I'll follow the exact STR to see if I can get it to happen. Otherwise this might be fixed already.

**Comment by SoftVision-CosminMuntean** [comment]
This issue was retested on the latest Nightly (49.0a1) build with Activity Stream v1.0.18 but it is reproducible only with e10s disabled.

The issue is reproducible also with this scenarios:
[Prerequisites]:
- Latest Activity Stream add-on version (1.0.18) was previously installed on a old profile.
- Have more history so that the "Highlights" area is populated with visited websites.
- Make sure that e10s is disabled.

[STR]:
1. Click on Activity Stream button from browser toolbar.
2. Press "SHITF + F2" to open the "Developer Toolbar".
3. Write "restart" in the console and press enter.

[Actual results]:
After the browser is restarted, the Mozilla start page is displayed for a few seconds and then it is replaced by Activity Stream Timeline. Activity Stream Timeline is empty although there is content in history. Even the Highlight tiles are hidden.

**Comment by sarracini** [comment]
So I looked at this and here's what I found using Nightly 49.0a1 and Activity Stream v1.0.19:

_With e10s enabled:_
1. **Can't** reproduce using Vlad's STR
2. **Can** reproduce using the "shift + f2" & restart way - but it's only the current page that was open when it restarted, meaning as soon as you open a new tab it corrects itself.

_With e10s disabled:_
1. **Can't** reproduce using Vlad's STR
2. **Can** reproduce using the "shift + f2" & restart way - but it's only the current page that was open when it restarted, meaning as soon as you open a new tab it corrects itself.

The shift + f2 + restart thing is super obscure, it seems unlikely that it's commonly used. Plus it corrects itself when you open a new tab, so in my opinion this bug is fixed

**Comment by SoftVision-CosminMuntean** [comment]
This issue was verified on the latest Nightly (49.0a1) build with Activity Stream v1.0.19-dev:

- With _e10s disabled_ the issue can be reproduced using Vlad's STR and "Shift + F2" restart way.
- With _e10s enabled_ the issue is not reproducible using Vlad's STR and "Shift + F2" restart way.

You can observe this behaviour [here](https://drive.google.com/open?id=0B70KzYmGg491SEhjSjdBNFI1aEE).

**Comment by SoftVision-VladBacia** [comment]
In Activity Stream v1.1.0-dev, after implementing #724 and fixing bug #849, the issue described above is reproducible more frequently on latest Nightly with e10s disabled and also in latest Firefox release. 
We observe that this issue is reproducible when the Activity Stream add-on is loaded a bit slower on browser startup. The rate of reproducibility for this issue was 5 out of 5 tries.

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160704030211) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.
