### ISSUE TITLE
Filter certain sites that are too common or obvious

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/activity-stream#681]
~~We are complicit in reporting and spying on ourselves and our peers.~~ We're always on facebook and twitter, and google.com. These are arguably unhelpful to have in our activity stream, since they can basically be assumed at this point. ~~Let's stop perpetuating a feedback loop of population control through cybernetics.~~ Maybe we could filter out on some of these __super__ common sites.

**Comment by pdehaan** [comment]
Not sure how this works. I may want to find that Google Search I was doing 4 hours ago, or try to remember some recent Facebook video about Hummus that I was watching yesterday.

I think our best bet may be the more versatile option of the blocklist where we can let the user ignore domain patterns (rather than having us trying to maintain a single list of sites we _assume_ you don't want to see ~~because @meandavejustice is apparently a top secret spy~~).

**Comment by meandavejustice** [comment]
@pdehaan I'm not proposing blocking `google.com/*`.  Just the google homepage.

**Comment by pdehaan** [comment]
Possibly valid, Dave. _Possibly_.

**Pro-tip:** If you find _just_ the [Google/Yahoo!/Reddit] homepage offensive in your results, we do have some initial blocking functionality if you hover+click the X icon in Highlights and select "Remove from History" (which is pretty brute force and actually deletes your history -- just as it says), or "Never show on this page" option which keeps it in your history but stops it appearing in results.

You should also have the same pop-up options available in the timeline view if you hover over a row and select the "X" icon.

**Comment by meandavejustice** [comment]
oh wonderful, thanks @pdehaan

**Comment by pdehaan** [comment]
No problem, @meandavejustice! I didn't build this stuff, I just steal all the credit when it works.

![](http://www.teamworkandleadership.com/wp-content/uploads/2015/02/teamwork-story-teamwork-makes-the-dreamwork.jpg)

**Comment by sarracini** [comment]
Feature requests should be added to the trello board
