### ISSUE TITLE
Remove newOnly in PreviewProvider.js

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#694]
This is not being used, please remove it:

https://github.com/mozilla/activity-stream/blob/master/lib/PreviewProvider.js#L217-L219

**Comment by sarracini** [comment]
@oyiptong unless we're missing something that it's used for?

**Comment by oyiptong** [comment]
At some point, it was discussed to have previews always for Highlights, which is why this option is here.

Unsure what's the status of that conversation. I'd err on the side of performance and remove the option, but I'd double check with @nchapman.

Basically, @nchapman, we can block links until there are previews. Previews may take 30 secs or more to get populated.

We have decided for release to not block, favoring performance, I.e users seeing their history even if it means there are no images.

Will there ever be a need to block links until they have previews?

**Comment by pdehaan** [comment]
Need feedback from @nchapman

**Comment by sarracini** [comment]
Fixed with #867
