### ISSUE TITLE
Clicking on "X" should just dismiss site from activity stream, not give me a bunch of options

### ISSUE THREAD

**Issue by wlach** [mozilla/activity-stream#701]
I wish clicking "X" would just dismiss the site from highlights, rather than force me to make a choice on "removing from history" or "never to show on this page"

<img width="263" alt="screen shot 2016-05-14 at 3 28 23 pm" src="https://cloud.githubusercontent.com/assets/20569/15270310/9fb76bda-19e8-11e6-9191-2e9a490f4b45.png">

If I visited the site again, I might want to see it again (though the fact that I just dismissed it is a strong hint that I might not)! It just might not be relevant now. I imagine for a non-technical audience these options are going to be even more confusing. In any case, I think forcing me to take some kind of destructive action to remove those sites/links is not a great user experience, at least for me.

**Comment by edangor** [comment]
I agree

**Comment by ciprianmuresan** [comment]
If we decide to keep or change this flow, we should also take into consideration the next scenario observed on the current implementation:

1. Hover an item from Highlights, Top Sites or Recent Activity sections.
2. Click on "X" button and choose "Remove from History".
3. Click "Cancel" and repeat step 2.
4. When the second dialog appears, click the "Prevent this page from creating additional dialogs" checkbox.
5. Click either "Ok" or "Cancel".

With that checkbox enabled we can no longer remove items from History, because we don't let the page create any more dialogs. 
I am afraid users might encounter this scenario due to the fact that when trying to remove multiple items from History, they might think that the checkbox is there in order to make the dialog save his preference of confirming that he wants to remove the page. 
However, page refresh resets the "generate dialogs" preference and users will be able to perform again the blocked actions.
![generate dialogs preference](https://cloud.githubusercontent.com/assets/18304511/15399124/1b1b88ec-1def-11e6-9527-520b97715a2f.png)

**Comment by bryanbell** [comment]
we totally agree, and this is high on our list of things to address in the short term. Beyond removing items, sharing and setting reminders are a few other things you might want to do with. the UI needs to be flexible. I'm working on new mocks now, and I'll post them here.

**Comment by bryanbell** [comment]
> With that checkbox enabled we can no longer remove items from History, because we don't let the page create any more dialogs. 

Thanks for the heads-up on this. This for sure needs to be addressed.

**Comment by bryanbell** [comment]
![context menu 1x](https://cloud.githubusercontent.com/assets/228979/15623385/b797fc1c-2427-11e6-8b74-d536614a591b.png)

**Comment by bryanbell** [comment]
Mockup for Top Site Management https://invis.io/YR76EYDBZ#/163224753_TopSite
