### ISSUE TITLE
Version number and date are not updated in Test Pilot for Activity Stream after a new release has been made

### ISSUE THREAD

**Issue by SoftVision-VladBacia** [mozilla/activity-stream#756]
In Test Pilot, the version and date for Activity Stream are still v1.0.16 and 5/23/2016 after the last production release although the new version of Activity Stream is v1.0.18 and was made in 5/26/2016.

![version and date of activity stream are not updating in test pilot](https://cloud.githubusercontent.com/assets/9248513/15607969/69bd9a2c-241f-11e6-9130-f752720fb47d.jpg)

[Expected]:
When a new production release is made, the version and date are automatically updated.

**Comment by pdehaan** [comment]
Unfortunately Test Pilot doesn't auto-update the version numbers yet, and it's still a manual process by Test Pilot admins. (ref https://github.com/mozilla/testpilot/issues/716 and https://github.com/mozilla/testpilot/issues/547).

@edmoz: Are you a Test Pilot prod admin, or should I bug @ckprice to bump the version number?

Closing (since this is tracked as an upstream Test Pilot enhancement).
