### ISSUE TITLE
Bug 1276932 - Infinite scrolling is not working after zooming out the Timeline page, if the scrollbar is not available

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#774]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1276932
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.18

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (v1.0.18) was previously installed on an old profile.
- Have enough History and Bookmarks in the profile so when scrolling is performed, a new batch of History items is listed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open Activity Stream Timeline from the browser toolbar.
3. Zoom out the Timeline page at lest 50%.
4. Refresh the Timeline page.

[Expected result]:
- Websites that were not displayed in viewport are listed while scrolling.

[Actual result]:
- Websites that were not displayed in viewport are not listed while scrolling because the scrollbar is not available.

[Notes]:
- This issue is reproducible when after zooming out the scroll bar is no longer displayed.
- On 4k monitors, this issue is reproducible instantly. When accessing Activity Stream Timeline there is no scroll bar and the user cannot load more visited websites while scrolling. 
- Attached a screen recording of the issue (https://goo.gl/01eYdy).

**Comment by SoftVision-VladBacia** [comment]
This issue was verified on Windows 8.1 x64 with latest Nightly (49.0a1, Build ID: 20160602030220) using Activity Stream v1.0.18-today build, and it is still reproducible.

[Prerequisites]:
- The browser window is in Fullscreen mode (1920x1080).
- Open a New Tab page and set the zoom level to 30%.

[STR]:
1. Click on Activity Stream button from the browser toolbar.
2. Scroll through the Timeline History items.
3. Click on Bookmarks button from the Timeline sidebar.
4.  Scroll through the Activity Stream Bookmark History items.

[Expected]:
- When scroll action is performed, more items are loaded.

[Actual]:
- When opening the Activity Stream Timeline, two batches of items are displayed but they are not enough to fill page.
- When switching between pages (Bookmarks and Timeline) a refresh should be automatically made, so the new items will be auto displayed. Every switch between pages requires a manual refresh in order to bring two batches of items but they are not enough.

[Notes]:
- [Here](https://goo.gl/1wXpj4) is a video of this behavior.

**Comment by rlr** [comment]
This fix goes out in v1.0.19 which *should* be out already or soon.

**Comment by rlr** [comment]
I see. Yes. There are still some issues with this. One is that we only load one extra batch assuming that should fill the page but in your case it doesn't. The other is when switching between history and bookmarks we aren't triggering that logic... I think one more small tweak will do the trick.

**Comment by SoftVision-VladBacia** [comment]
I have tested this issue on latest Firefox release v47.0 and latest Nightly 50.0a1 (Build ID: 20160616163918) using Activity Stream v1.1.0 and could not reproduce it. I have set the Timeline History page zoom to 30% and also set a 4K monitor in portrait mode, all worked as expected.
