### ISSUE TITLE
Collect Uninstall Event Pings

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#790]

**Comment by ncloudioj** [comment]
Due to a known [bug 627432](https://bugzilla.mozilla.org/show_bug.cgi?id=627432), the addon is unable to capture the "uninstall" event, instead, it'll get a "disable" event when the user uninstalls the addon (see more [here](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Listening_for_load_and_unload)).

Can we treat both the "disable" and "uninstall" as the same event here? In that case, it simply fires a "uninstall" ping to the server, which means the user has decided not to use the addon now. If she re-enables or re-installs the addon, everything just works as usual. 

@emtwo @tspurway @oyiptong What do you think?

**Comment by oyiptong** [comment]
I think a `disable` ping is fine as an event to track

**Comment by oyiptong** [comment]
It's the best we can do anyway :-) I think `disable` as the event name works well, as that's the event we'll be tracking in the addon anyway.

**Comment by ncloudioj** [comment]
Yes, I think we can use "disable" other than "uninstall" for this, as the best effort. Thanks for confirming it!
