### ISSUE TITLE
Bug 1279226 - "Dismiss" button is missing from the context menu in Timeline History and Bookmarks pages

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#814]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279226
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19) was previously installed on a profile.
- Have several visited websites, that are displayed in Activity Stream Timeline History page.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Activity Stream button from the browser toolbar.
3. Move the mouse cursor over a visited item.
4. Click on "..." button.
5. Observe the "Dismiss" option.

[Expected result]:
- "Dismiss" button is present in the context menu.

[Actual result]:
- "Dismiss" button is missing from the context menu

[Notes]:
- This issue is also reproducible on Timeline Bookmarks page.
![dismiss button](https://cloud.githubusercontent.com/assets/17258026/15934805/8b6616ec-2e6d-11e6-8d58-83d3ddc296b2.png)

**Comment by pdehaan** [comment]
@k88hudson This may be a regression with the new context menu work. Is this an easy fix, or should we push to a post-London milestone?

**Comment by k88hudson** [comment]
This is intended behaviour (dismiss is for the New Tab page only)

**Comment by SoftVision-CosminMuntean** [comment]
While testing the latest Activity Stream add-on (v1.1.0) we observed that the "Dismiss" button is present for "Highlights" tiles from Timeline page.

From our point of view the user shouldn't be restricted in doing the "Dismiss" action only from New Tab page. The New Tab page has a limited number of items displayed, so older visited pages must be revisited in order to block them. From Timeline History the user can scroll through all the visited websites and block the desired ones.
We've understand that if a website is blocked, then that website will never be displayed in Timeline, even if it's visited countless times. As for the delete option , it must be used every time after the website is visited, in order to hide the visits.

@k88hudson, can you please provide more information about the latest changes regarding the 'Dismiss" functionality? And related to the last comment, should the "Dismiss" button be missing from "Highlights" tiles and "Timeline History", or just from "Timeline History"?
