### ISSUE TITLE
Limit the number of videos that show up on new tab

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#852]
Right now many videos can show up on new tab. It's kind of overwhelming. I suggest we limit this to 1 video.

**Comment by pdehaan** [comment]
I'd rather do something like https://github.com/mozilla/activity-stream/pull/755#issuecomment-222219540 (collapsible previews or ability to delete a preview &mdash; see below). But I think limiting the number of previews [to one] is probably overkill and would make the feature less usable.

> Not sure if we're going to need to make a collapsable UI or add the ability to delete a preview. After a bit of testing and YouTube-in' my timeline will get pretty cluttered up.

But I think something like [Min-Vid](https://github.com/meandavejustice/min-vid) may solve the lack of previews issue (since I could just right click the video link and pop out the video into a separate player).
