### ISSUE TITLE
first run after addon update results in 'hang on' message forever

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#891]
1. use a profile with an average amount of history and data.
2. install dev channel activity stream
3. upgrade via about:addons UI or automatically after 24hr ping
4. launch new tab

actual: the view displays 'hang on tight' for a long long time.  work around is refresh the browser.

expected: it should only sit on 'hang on tight for maybe 5-10sec.

**Comment by rlr** [comment]
@edmoz is this 100% reproducible for you?

I installed v1.0.19 (from https://s3.amazonaws.com/moz-activity-streams/dist/activity_streams_experiment-1.0.19-fx.xpi) on my every day since forever Firefox profile. I opened a new tab and everything worked. Then I went to the about:addons and checked for updates and it updated to v.1.1.0. Opened a new tab and it still worked and was pretty fast.

I tried on both:  Firefox dev edition and release (47.0.1).

**Comment by edmoz** [comment]
hmm - i'm unable to repro... when i manually disable/enable/uninstall/reinstall.

are you seeing the 'hang on tight message' at all.  I'm not sure a reliable way to trigger that.

**Comment by rlr** [comment]
I haven't ever seen the "hang on tight" message except for that one time there were embedly/proxy issues. Maybe it's because my machine and internet are too fast?

**Comment by rlr** [comment]
@edmoz actually, I get a hang on tight message if I am on the new tab page and restart my browser with the "show my windows and tabs from last time" preference selected. I remember @nchapman mentioning the issue in the meeting. Maybe that's what we wanted to file? Or is that a separate issue?

**Comment by edmoz** [comment]
does the hang on tight go away after a few seconds or just persist.  I'm down grading this to P2 since it's hard to discover.

**Comment by nchapman** [comment]
There's a race condition when starting Firefox where I see this issue on a regular basis. There are various circumstances where it gets stuck in this state:

<img width="1392" alt="screenshot 2016-06-28 23 50 05" src="https://cloud.githubusercontent.com/assets/3095/16443037/3f30d6f4-3d8b-11e6-997f-8d97d93c9523.png">

**Comment by SoftVision-VladBacia** [comment]
This issue is similar with the behavior that we encountered in #674 and detailed [here](https://github.com/mozilla/activity-stream/issues/674#issuecomment-228312587).

After implementing #724 and fixing bug #849, the 'hang on' message is displayed every time the browser is started with **_e10s disabled_**. With _e10s enabled_ we didn't encounter this issue.
