### ISSUE TITLE
Highlights displaying URLs as titles

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#971]
In some situations, a highlight card is failing to show a title and showing the URL instead.  We need to figure out how/why this is happening.  

![pasted image at 2016_07_26 09_55 am](https://cloud.githubusercontent.com/assets/119884/17149048/9bc10332-5337-11e6-9aaf-fb164abd8226.png)

**Comment by jaredkerim** [comment]
We decided this should be backlogged.

**Comment by pdehaan** [comment]
I was playing w/ hitting the Embedly proxy directly and think I can possibly explain this...
It looks like if Embedly doesn't have a cached result for the specified URL, it returns an empty object, or maybe it's our proxy... Regardless, here are my HTTPie results with timestamps:


# _REQUEST 1:_ Thu, 18 Aug 2016 22:58:46 GMT

```sh
$ http https://embedly-proxy.services.mozilla.com/v2/extract urls:='["http://yogimami.com/Empire/tag/homemade-charcoal-lemonade-juice/"]' -j -v

POST /v2/extract HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 78
Content-Type: application/json; charset=utf-8
Host: embedly-proxy.services.mozilla.com
User-Agent: HTTPie/0.9.1

{
    "urls": [
        "http://yogimami.com/Empire/tag/homemade-charcoal-lemonade-juice/"
    ]
}

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 25
Content-Type: application/json
Date: Thu, 18 Aug 2016 22:58:46 GMT

{
    "error": "",
    "urls": {}
}
```

---

# _REQUEST 2:_ Thu, 18 Aug 2016 22:58:59 GMT
(about 13 seconds after initial request)

```sh
$ http https://embedly-proxy.services.mozilla.com/v2/extract urls:='["http://yogimami.com/Empire/tag/homemade-charcoal-lemonade-juice/"]' -j -v

POST /v2/extract HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 78
Content-Type: application/json; charset=utf-8
Host: embedly-proxy.services.mozilla.com
User-Agent: HTTPie/0.9.1

{
    "urls": [
        "http://yogimami.com/Empire/tag/homemade-charcoal-lemonade-juice/"
    ]
}

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 7229
Content-Type: application/json
Date: Thu, 18 Aug 2016 22:58:59 GMT

{
    "error": "",
    "urls": {
        "http://yogimami.com/Empire/tag/homemade-charcoal-lemonade-juice/": {
            "app_links": [],
            "authors": [
                {
                    "name": "View all posts by",
                    "url": "http://yogimami.com/Empire/author/administrator/"
                }
            ],
            "cache_age": 86400,
            "content": "<div>...</div>",
            ...
            "language": "English",
            "lead": null,
            "media": {},
            "offset": null,
            "original_url": "http://yogimami.com/Empire/tag/homemade-charcoal-lemonade-juice/",
            "provider_display": "yogimami.com",
            "provider_name": "Yogi Mami",
            "provider_url": "http://yogimami.com",
            "published": null,
            "related": [],
            "safe": true,
            "title": "homemade charcoal lemonade juice Archives - Yogi Mami",
            "type": "html",
            "url": "http://yogimami.com/Empire/tag/homemade-charcoal-lemonade-juice/"
        }
    }
}
```

Note that in the second request, I get `"cache_age": 86400`, which is 24 hours; assuming `cache_age` is seconds, per http://docs.embed.ly/docs/extract:

> `cache_age` &mdash; How long Embedly is going to cache the response for? Generally, this is for a day, unless some external factor tells us to reevaluate the resource.

I'd have to dig in further and try hitting the Embed.ly API directly with a cache miss to see if the API is returning the empty object, or if it is our proxy... But at least that explains why my scrapers were occasionally giving me errors because of trying to access properties on null/undefined objects.

But preliminarily it looks like Embedly returns cached results, if available whereas the Fathom/metadata server is making requests directly to the target URL each time and blocking until it gets a response. Which is why the metadata server sometimes takes 4-5x longer to return results, but returns them consistently.

**Comment by ianb** [comment]
Noted in one of the dups, this happens to me primarily (and regularly) with articles that I read on my phone and are sync'd over.

**Comment by edmoz** [comment]
Seems to happen when the proxy server returns: {u'error': u'', u'urls': {}} , though a subsequent fetch does get the page metadata.

**Comment by pdehaan** [comment]
@edmoz @jaredkerim Why would a proxy server return that seemingly null payload? Is the Embedly/Metadata proxies taking too long to respond? Or is that some Embedly behavior where if it isn't in cache, it returns an empty response and the next request serves page metadata because by that point it's a cache hit?

**Comment by edmoz** [comment]
@pdehaan if the server is taking to long or isn't url cached - it returns empty. Future requests will return cached results.  I believe the client should not display if there's no title, unless there are no other cards to display are available (there might be a bug here).

**Comment by jaredkerim** [comment]
@pdehaan You are exactly right.  The embedly-proxy only serves data out of the cache to requesters, and so if there is no data found in the cache it returns an empty result while it fetches the data as an async task.  The client will then re request the data which it does find in the cache and receives.  The first request for an uncached URL will always return an empty result.

**Comment by ianb** [comment]
Note that in these examples there *is* metadata: an image and article summary.  So it's not an example of a null response.  My theory is that at some point the title is being defaulted to the URL and the metadata doesn't overwrite that default.

**Comment by sarracini** [comment]
This is now fixed
